/**
 * Fast offline tests for the discovery-mode CLI wiring: the pure coverage
 * policy (classifyCoverage) and the runGenerate discovery loop's offline
 * branches — empty-lockfile warn+skip, zero-targets error, and --exclude
 * semantics. Plus the `--policy` wiring tests: absent-flag byte-identity,
 * document-written-despite-fail, the fail-fast invalid-policy path, the stderr
 * verdict summary, and the annotated dump-model surface.
 *
 * Every test here is subprocess-free by construction: empty lockfiles are
 * classified and skipped before any scanner dispatch, so no generator is ever
 * spawned and the suite stays well under the fast-suite budget. The policy
 * tests need packages in the model, so they stub collectWithCdxgen via
 * mock.module with a fixture-SBOM writer (restored in afterAll) — the real
 * runGenerate pipeline runs end-to-end, minus the subprocess.
 */

import { spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, mock, test } from "bun:test";

import { exitCodeFor, runCheck } from "../src/gate/check";
import { classifyCoverage, coverageSkipReason } from "../src/pipeline/coverage";
import { defaultNoticesPath, resolveFrom } from "../src/pipeline/paths";
import { buildOutputs, runGenerate } from "../src/pipeline/pipeline";
import { sanitizeForLog, writePolicySummary } from "../src/pipeline/summary";
import { parsePolicy } from "../src/policy/schema";
import { MAX_BUN_LOCK_BYTES } from "../src/collectors/bunLock";
import * as cdxgenModule from "../src/collectors/cdxgen";
import type { Verdict } from "../src/model/dependencies";

/**
 * A legitimate zero-dependency Yarn-4 lockfile: non-empty (always contains
 * `__metadata:` plus the project's own workspace self-entry) but with zero
 * third-party entries — the false-positive shape.
 */
const NO_DEPS_V8_LOCKFILE = [
  '# This file is generated by running "yarn install" inside your project.',
  "# Manual changes might be lost - proceed with caution!",
  "",
  "__metadata:",
  "  version: 8",
  "  cacheKey: 10c0",
  "",
  '"proj@workspace:.":',
  "  version: 0.0.0-use.local",
  "  languageName: unknown",
  "  linkType: soft",
  "",
].join("\n");

/**
 * Capture process.stderr.write for the duration of a callback; always
 * restores in finally so a failing assertion can never poison later tests.
 */
async function withCapturedStderr(fn: () => Promise<void>): Promise<string> {
  const original = process.stderr.write.bind(process.stderr);
  let captured = "";
  process.stderr.write = ((chunk: unknown): boolean => {
    captured += String(chunk);
    return true;
  }) as typeof process.stderr.write;
  try {
    await fn();
  } finally {
    process.stderr.write = original;
  }
  return captured;
}

/** Temp repo root holding one yarn project with a 0-byte yarn.lock. */
function makeEmptyLockfileTree(): { root: string; identity: string } {
  const root = mkdtempSync(join(tmpdir(), "licenses-cli-"));
  const projDir = join(root, "proj");
  mkdirSync(projDir);
  writeFileSync(join(projDir, "package.json"), "{}\n");
  writeFileSync(join(projDir, "yarn.lock"), "");
  return { root, identity: "proj" };
}

const squish = (s: string): string => s.replace(/ {2,}/g, " ");

describe("classifyCoverage — coverage policy (pure)", () => {
  test("empty lockfile text classifies as skip", () => {
    expect(classifyCoverage("apps/x", "yarn.lock", "", 0)).toBe("skip");
  });

  test("whitespace-only lockfile text classifies as skip", () => {
    expect(classifyCoverage("apps/x", "yarn.lock", " \n\t\n", 7)).toBe("skip");
  });

  test("non-empty lockfile with zero components throws naming target and lockfile", () => {
    let thrown: Error | undefined;
    try {
      classifyCoverage("apps/jupyter", "poetry.lock", "[[package]]\n", 0);
    } catch (error) {
      thrown = error as Error;
    }
    expect(thrown).toBeDefined();
    expect(thrown!.message).toContain("apps/jupyter");
    expect(thrown!.message).toContain("poetry.lock");
  });

  test("non-empty lockfile with components classifies as include", () => {
    expect(
      classifyCoverage(
        "frontend",
        "yarn.lock",
        '__metadata:\n  version: 8\n"lodash@npm:^4.17.21":\n  version: 4.17.21\n',
        1593,
      ),
    ).toBe("include");
  });

  test("zero-dependency Yarn-4 lockfile with zero components classifies as skip, not throw", () => {
    expect(
      classifyCoverage("apps/no-deps", "yarn.lock", NO_DEPS_V8_LOCKFILE, 0),
    ).toBe("skip");
  });

  test("a poetry lockfile WITH [[package]] entries that scans to zero components stays the hard error", () => {
    // The relaxation only covers lockfiles with zero third-party [[package]]
    // tables — a parse/scan failure on a populated lockfile is exactly the
    // silent-incomplete-inventory case the coverage policy exists to catch.
    expect(() =>
      classifyCoverage("apps/jupyter", "poetry.lock", "[[package]]\n", 0),
    ).toThrow("coverage assertion failed");
  });

  test("a dependency-free poetry.lock (metadata only) classifies as skip, not throw", () => {
    const lockfile = [
      "[metadata]",
      'lock-version = "2.1"',
      'python-versions = ">=3.12"',
      "",
    ].join("\n");
    expect(classifyCoverage("apps/pyfree", "poetry.lock", lockfile, 0)).toBe(
      "skip",
    );
  });

  test("a dependency-free uv.lock (only the local self entry) classifies as skip, not throw", () => {
    const lockfile = [
      "version = 1",
      "",
      "[[package]]",
      'name = "myproject"',
      'version = "0.1.0"',
      'source = { virtual = "." }',
      "",
    ].join("\n");
    expect(classifyCoverage("apps/uvfree", "uv.lock", lockfile, 0)).toBe(
      "skip",
    );
  });

  test("skip classification cannot drift: every coverageSkipReason skip is an classifyCoverage skip", () => {
    // The loop's pre-scan skip uses coverageSkipReason; the post-scan gate uses
    // classifyCoverage's verdict. Both must agree for every skip-classified
    // input even at the would-throw componentCount of 0 — a divergence here is
    // a silent policy inversion.
    const skipClassified: Array<[string, string]> = [
      ["yarn.lock", ""],
      ["yarn.lock", " \n\t\n"],
      ["poetry.lock", "   \n"],
      ["yarn.lock", NO_DEPS_V8_LOCKFILE],
      ["poetry.lock", '[metadata]\nlock-version = "2.1"\n'],
      [
        "uv.lock",
        'version = 1\n\n[[package]]\nname = "p"\nsource = { virtual = "." }\n',
      ],
    ];
    for (const [lockfileName, lockfileText] of skipClassified) {
      expect(coverageSkipReason(lockfileName, lockfileText)).toBeDefined();
      expect(classifyCoverage("apps/x", lockfileName, lockfileText, 0)).toBe(
        "skip",
      );
    }
  });
});

// ---------------------------------------------------------------------------
// coverageSkipReason — the npm/pnpm/bun branches. The rule under test: only a
// positively-determined zero third-party count takes the warn+skip branch; an
// unknown count (v1/garbage) returns undefined so the target routes to the
// scan and a zero-component result hard-fails loudly (never a silent skip).
// ---------------------------------------------------------------------------

/** v3 lockfile with one real third-party entry (scan, never skip). */
const NPM_V3_WITH_DEPS = JSON.stringify({
  name: "npm-app",
  lockfileVersion: 3,
  packages: {
    "": { name: "npm-app", version: "1.0.0" },
    "node_modules/express": { version: "5.2.1", license: "MIT" },
  },
});

/** v3 lockfile with ONLY the project root entry (positively zero → skip). */
const NPM_V3_ROOT_ONLY = JSON.stringify({
  name: "npm-app",
  lockfileVersion: 3,
  packages: { "": { name: "npm-app", version: "1.0.0" } },
});

/** v3 workspace lockfile whose only node_modules entries are link:true. */
const NPM_V3_LINKS_ONLY = JSON.stringify({
  name: "npm-ws",
  lockfileVersion: 3,
  packages: {
    "": { name: "npm-ws", version: "1.0.0" },
    "packages/liba": { version: "0.1.0" },
    "node_modules/liba": { resolved: "packages/liba", link: true },
  },
});

/** Legacy v1 lockfile: NO packages map → UNKNOWN count → route to scan. */
const NPM_V1_LOCKFILE = JSON.stringify({
  name: "legacy-app",
  version: "1.0.0",
  lockfileVersion: 1,
  dependencies: { express: { version: "5.2.1" } },
});

/** v9 lockfile with a packages: section (scan, never skip). */
const PNPM_V9_WITH_PACKAGES = [
  "lockfileVersion: '9.0'",
  "",
  "importers:",
  "",
  "  .:",
  "    dependencies:",
  "      smol-toml:",
  "        specifier: ^1.6.1",
  "        version: 1.6.1",
  "",
  "packages:",
  "",
  "  smol-toml@1.6.1:",
  "    resolution: {integrity: sha512-aaa}",
  "",
].join("\n");

/** Workspace-only v9 lockfile: importers, NO packages: section → skip. */
const PNPM_V9_IMPORTERS_ONLY = [
  "lockfileVersion: '9.0'",
  "",
  "importers:",
  "",
  "  .: {}",
  "",
].join("\n");

/** bun.lock whose only packages entry is an @workspace: member → skip. */
const BUN_WORKSPACE_ONLY_LOCK = `{
  "lockfileVersion": 1,
  "workspaces": {
    "": { "name": "bun-root" },
    "packages/libb": { "name": "libb", "version": "0.1.0" },
  },
  "packages": {
    "libb": ["libb@workspace:packages/libb"],
  },
}
`;

/** bun.lock with one third-party entry (scan, never skip). */
const BUN_WITH_THIRD_PARTY_LOCK = `{
  "lockfileVersion": 1,
  "workspaces": { "": { "name": "bun-root" } },
  "packages": {
    "smol-toml": ["smol-toml@1.6.1", "", {}, "sha512-bbb"],
  },
}
`;

describe("coverageSkipReason — npm/pnpm/bun branches", () => {
  test("package-lock.json v3 with third-party deps routes to scan", () => {
    expect(
      coverageSkipReason("package-lock.json", NPM_V3_WITH_DEPS),
    ).toBeUndefined();
  });

  test("package-lock.json v3 with only the root entry skips naming the lockfile", () => {
    const reason = coverageSkipReason("package-lock.json", NPM_V3_ROOT_ONLY);
    expect(reason).toBeDefined();
    expect(reason).toContain("package-lock.json");
    expect(reason).toContain("no third-party entries");
  });

  test("package-lock.json v3 with only workspace links skips (positively-determined zero)", () => {
    expect(
      coverageSkipReason("package-lock.json", NPM_V3_LINKS_ONLY),
    ).toBeDefined();
  });

  test("package-lock.json v1 (no packages map) routes to scan — unknown is never a skip", () => {
    // A v1 lockfile proves nothing about its entry count. The target must
    // scan; a zero-component scan then hard-fails loudly.
    expect(
      coverageSkipReason("package-lock.json", NPM_V1_LOCKFILE),
    ).toBeUndefined();
  });

  test("package-lock.json garbage routes to scan (unknown count)", () => {
    expect(
      coverageSkipReason("package-lock.json", "not json {"),
    ).toBeUndefined();
  });

  test("pnpm-lock.yaml v9 with a packages section routes to scan", () => {
    expect(
      coverageSkipReason("pnpm-lock.yaml", PNPM_V9_WITH_PACKAGES),
    ).toBeUndefined();
  });

  test("pnpm-lock.yaml importers-only skips naming the lockfile", () => {
    const reason = coverageSkipReason("pnpm-lock.yaml", PNPM_V9_IMPORTERS_ONLY);
    expect(reason).toBeDefined();
    expect(reason).toContain("pnpm-lock.yaml");
    expect(reason).toContain("no third-party entries");
  });

  test("bun.lock workspace-only skips naming the lockfile", () => {
    const reason = coverageSkipReason("bun.lock", BUN_WORKSPACE_ONLY_LOCK);
    expect(reason).toBeDefined();
    expect(reason).toContain("bun.lock");
    expect(reason).toContain("no third-party entries");
  });

  test("bun.lock with third-party entries routes to scan", () => {
    expect(
      coverageSkipReason("bun.lock", BUN_WITH_THIRD_PARTY_LOCK),
    ).toBeUndefined();
  });

  test("bun.lock garbage routes to scan — the collector throws loudly later", () => {
    expect(coverageSkipReason("bun.lock", "garbage {{{")).toBeUndefined();
  });

  test("empty/whitespace text for every new kind takes the existing empty reason", () => {
    for (const name of ["package-lock.json", "pnpm-lock.yaml", "bun.lock"]) {
      expect(coverageSkipReason(name, "")).toBe(
        `${name} is empty (whitespace only)`,
      );
      expect(coverageSkipReason(name, " \n\t\n")).toBe(
        `${name} is empty (whitespace only)`,
      );
    }
  });

  test("every new-kind skip is an classifyCoverage skip — extended to npm/pnpm/bun", () => {
    const skipClassified: Array<[string, string]> = [
      ["package-lock.json", NPM_V3_ROOT_ONLY],
      ["package-lock.json", NPM_V3_LINKS_ONLY],
      ["pnpm-lock.yaml", PNPM_V9_IMPORTERS_ONLY],
      ["bun.lock", BUN_WORKSPACE_ONLY_LOCK],
    ];
    for (const [lockfileName, lockfileText] of skipClassified) {
      expect(coverageSkipReason(lockfileName, lockfileText)).toBeDefined();
      expect(classifyCoverage("apps/x", lockfileName, lockfileText, 0)).toBe(
        "skip",
      );
    }
  });
});

describe("sanitizeForLog — stderr injection boundary", () => {
  // Control characters are BUILT, never typed literally, so this file stays
  // control-char free on disk.
  const ESC = String.fromCharCode(27); // 0x1B
  const DEL = String.fromCharCode(127); // 0x7F
  const CSI = String.fromCharCode(155); // 0x9B (C1 single-byte CSI)

  test("newline injection cannot forge a summary line", () => {
    const forged =
      "ok\npolicy: 0 fail, 0 warn, 0 suppressed, 9999 ok (9999 verdicts)";
    const out = sanitizeForLog(forged);
    expect(out).not.toContain("\n");
    expect(out).toBe(
      "ok policy: 0 fail, 0 warn, 0 suppressed, 9999 ok (9999 verdicts)",
    );
  });

  test("ANSI erase/cursor sequences are neutralized (ESC flattened)", () => {
    const out = sanitizeForLog(`real${ESC}[2K${ESC}[1Aforged`);
    expect(out).not.toContain(ESC);
    expect(out).toBe("real [2K [1Aforged");
  });

  test("CR, tab, DEL, and C1 controls are flattened to spaces", () => {
    expect(sanitizeForLog(`a\rb\tc${DEL}d${CSI}e`)).toBe("a b c d e");
  });

  test("plain printable text — incl. the em dash — passes through unchanged", () => {
    const clean =
      'policy fail: pkg:npm/x@1.0.0 in proj — default:copyleft: copyleft license "AGPL-3.0-only"';
    expect(sanitizeForLog(clean)).toBe(clean);
  });

  test("oversized fields are capped with a truncation marker", () => {
    const out = sanitizeForLog("x".repeat(2000));
    expect(out.length).toBeLessThan(600);
    expect(out.endsWith("...[truncated]")).toBe(true);
  });
});

describe("writePolicySummary — imprecise count line (INV-04)", () => {
  const impreciseVerdict = (rule: string): Verdict => ({
    purl: "pkg:pypi/imp@1.0.0",
    occurrenceTarget: "apps/jupyter",
    status: "warn",
    rule,
    reason: "imprecise family",
  });

  test("an imprecise count line is added without reshaping the locked counts line", async () => {
    const verdicts: Verdict[] = [
      impreciseVerdict("default:imprecise"),
      impreciseVerdict("default:imprecise-copyleft"),
    ];
    const stderr = await withCapturedStderr(async () => {
      writePolicySummary(parsePolicy(""), verdicts, new Set());
    });
    // The locked counts-line shape is intact (both imprecise verdicts are warns).
    expect(stderr).toContain(
      "policy: 0 fail, 2 warn, 0 suppressed, 0 ok (2 verdicts)\n",
    );
    // ...plus a NEW imprecise line. I1: the count is PER-OCCURRENCE (matching
    // the `(M verdicts)` denominator, NOT the per-package markdown section), so
    // the line carries an explicit "(N verdicts)" suffix mirroring that shape.
    expect(stderr).toContain(
      "policy: 2 imprecise (review / disambiguate via [[clarify]]) " +
        "(2 verdicts)\n",
    );
  });

  test("no imprecise line is printed when there are no imprecise verdicts", async () => {
    const verdicts: Verdict[] = [
      {
        purl: "pkg:npm/x@1.0.0",
        occurrenceTarget: "proj",
        status: "ok",
        rule: "default:ok",
        reason: "no copyleft",
      },
    ];
    const stderr = await withCapturedStderr(async () => {
      writePolicySummary(parsePolicy(""), verdicts, new Set());
    });
    expect(stderr).toContain(
      "policy: 0 fail, 0 warn, 0 suppressed, 1 ok (1 verdicts)\n",
    );
    expect(stderr).not.toContain("imprecise");
  });
});

describe("resolveFrom — base-dir path anchoring (CR-01)", () => {
  test("relative paths join the base; absolute paths pass through; absent base degrades to cwd", () => {
    const base = tmpdir();
    expect(resolveFrom(base, "policy.toml")).toBe(join(base, "policy.toml"));
    const absolute = join(base, "abs.md");
    expect(resolveFrom(base, absolute)).toBe(absolute);
    expect(resolveFrom(undefined, "x.md")).toBe(resolve(process.cwd(), "x.md"));
  });
});

describe("runGenerate discovery mode — offline branches", () => {
  test("empty-lockfile target is loudly skipped and the run resolves with a zero-count document", async () => {
    const { root, identity } = makeEmptyLockfileTree();
    const outputPath = join(root, "out.md");

    const stderr = await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        outputPath,
        noticesPath: join(root, "notices.md"),
        verbose: false,
      });
    });

    expect(readFileSync(outputPath, "utf8")).toContain("- Total packages: 0");
    expect(stderr).toContain(identity);
    expect(stderr).toContain("is empty (whitespace only)");
  });

  test("a zero-dependency Yarn-4 target is loudly skipped without spawning a generator", async () => {
    // Non-empty yarn.lock (Yarn 4 always writes __metadata + the workspace
    // self-entry) with zero third-party entries must warn + skip and resolve —
    // never dispatch the yarn plugin (a real subprocess) and never hard-fail
    // the whole run via the coverage assertion.
    const root = mkdtempSync(join(tmpdir(), "licenses-cli-nodeps-"));
    const projDir = join(root, "proj");
    mkdirSync(projDir);
    writeFileSync(join(projDir, "package.json"), '{ "name": "proj" }\n');
    writeFileSync(join(projDir, "yarn.lock"), NO_DEPS_V8_LOCKFILE);
    const outputPath = join(root, "out.md");

    const stderr = await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        outputPath,
        noticesPath: join(root, "notices.md"),
        verbose: false,
      });
    });

    expect(readFileSync(outputPath, "utf8")).toContain("- Total packages: 0");
    expect(stderr).toContain("warning: skipping proj");
    expect(stderr).toContain("no third-party entries");
    expect(stderr).not.toContain("collecting");
  });

  test("zero discovered targets rejects naming --repo-root and the resolved path", async () => {
    const root = mkdtempSync(join(tmpdir(), "licenses-cli-empty-"));
    const outputPath = join(root, "out.md");

    let thrown: Error | undefined;
    await withCapturedStderr(async () => {
      try {
        await runGenerate({
          repoRoot: root,
          outputPath,
          noticesPath: join(root, "notices.md"),
          verbose: false,
        });
      } catch (error) {
        thrown = error as Error;
      }
    });

    expect(thrown).toBeDefined();
    expect(thrown!.message).toContain("--repo-root");
    expect(thrown!.message).toContain(resolve(root));
  });

  test("a target missing its manifest fails fast before any scan is dispatched", async () => {
    // poetry.lock without pyproject.toml: pre-fix this would spawn cdxgen
    // for up to the full timeout budget and only then throw from
    // computeCacheKey. The pre-check must reject immediately (this test is
    // offline — a dispatched scan would blow the fast-suite budget), naming
    // the target identity and the missing file.
    const root = mkdtempSync(join(tmpdir(), "licenses-cli-manifest-"));
    const projDir = join(root, "pyproj");
    mkdirSync(projDir);
    writeFileSync(join(projDir, "poetry.lock"), '[[package]]\nname = "x"\n');
    const outputPath = join(root, "out.md");

    let thrown: Error | undefined;
    await withCapturedStderr(async () => {
      try {
        await runGenerate({
          repoRoot: root,
          outputPath,
          noticesPath: join(root, "notices.md"),
          verbose: false,
        });
      } catch (error) {
        thrown = error as Error;
      }
    });

    expect(thrown).toBeDefined();
    expect(thrown!.message).toContain(
      'target "pyproj" is missing pyproject.toml',
    );
    expect(thrown!.message).toContain(join(projDir, "pyproject.toml"));
  });

  test("--exclude matching the project's identity removes it before discovery (no warning)", async () => {
    const { root, identity } = makeEmptyLockfileTree();
    const outputPath = join(root, "out.md");

    const stderr = await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        excludes: [identity],
        outputPath,
        noticesPath: join(root, "notices.md"),
        verbose: false,
      });
    });

    expect(readFileSync(outputPath, "utf8")).toContain("- Total packages: 0");
    expect(stderr).not.toContain("warning: skipping");
  });
});

describe("runGenerate discovery warnings (collision, bun.lockb)", () => {
  test("a bun.lock+package-lock.json dir warns ONCE naming the winner and is processed once", async () => {
    // Both lockfiles empty: the surviving bun target takes the empty-skip
    // branch, so the whole run stays offline (no generator ever spawns).
    const root = mkdtempSync(join(tmpdir(), "licenses-cli-collision-"));
    const projDir = join(root, "proj");
    mkdirSync(projDir);
    writeFileSync(join(projDir, "package.json"), '{ "name": "proj" }\n');
    writeFileSync(join(projDir, "bun.lock"), "");
    writeFileSync(join(projDir, "package-lock.json"), "");
    const outputPath = join(root, "out.md");

    const stderr = await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        outputPath,
        noticesPath: join(root, "notices.md"),
        verbose: false,
      });
    });

    // Exactly ONE collision warning, with the locked prefix and content.
    const collisionLines = stderr
      .split("\n")
      .filter((line) => line.includes("has multiple JS lockfiles"));
    expect(collisionLines.length).toBe(1);
    expect(collisionLines[0]).toContain(
      'warning: target "proj" has multiple JS lockfiles — scanning bun.lock',
    );
    expect(collisionLines[0]).toContain("ignoring package-lock.json");

    // The dir was processed ONCE (a single skip line for the winner) and
    // nothing was ever dispatched.
    const skipLines = stderr
      .split("\n")
      .filter((line) => line.startsWith("warning: skipping proj"));
    expect(skipLines.length).toBe(1);
    expect(skipLines[0]).toContain("bun.lock is empty (whitespace only)");
    expect(stderr).not.toContain("collecting");
    expect(readFileSync(outputPath, "utf8")).toContain("- Total packages: 0");
  });

  test("a bun.lockb-only dir warns naming the migration command and is never scanned", async () => {
    const root = mkdtempSync(join(tmpdir(), "licenses-cli-lockb-"));
    const binDir = join(root, "binproj");
    mkdirSync(binDir);
    writeFileSync(join(binDir, "package.json"), '{ "name": "binproj" }\n');
    writeFileSync(join(binDir, "bun.lockb"), " binary-lockfile-bytes");
    // A second, empty-yarn target keeps discovery non-empty so the run
    // resolves (bun.lockb itself is never a target).
    const otherDir = join(root, "other");
    mkdirSync(otherDir);
    writeFileSync(join(otherDir, "package.json"), '{ "name": "other" }\n');
    writeFileSync(join(otherDir, "yarn.lock"), "");
    const outputPath = join(root, "out.md");

    const stderr = await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        outputPath,
        noticesPath: join(root, "notices.md"),
        verbose: false,
      });
    });

    expect(stderr).toContain(
      'warning: target "binproj" has a binary bun.lockb',
    );
    expect(stderr).toContain("bun install --save-text-lockfile");
    // binproj never became a target: no skip line for it, no dispatch at all.
    expect(stderr).not.toContain("warning: skipping binproj");
    expect(stderr).not.toContain("collecting");
    expect(readFileSync(outputPath, "utf8")).toContain("- Total packages: 0");
  });
});

// ---------------------------------------------------------------------------
// --policy wiring. These tests need packages in the model, so
// collectWithCdxgen is stubbed to write a fixture SBOM — no subprocess, but the
// full runGenerate pipeline (discovery, dispatch, coverage, merge, policy,
// render, write) runs for real. Restored in afterAll so later test files see
// the genuine scanner.
// ---------------------------------------------------------------------------

/** Original exports captured BEFORE any mock.module call (restore target). */
const REAL_CDXGEN = { ...cdxgenModule };

/**
 * Fixture SBOM the stubbed scanner returns: one copyleft package (AGPL,
 * no rule will cover it → fail), one claim-less package (→ unknown →
 * [unknown] handling), one permissive package (→ default:ok). Verdict
 * order is compareCodeUnits on purl: copyleft-lib < mit-lib < no-claims.
 */
const FIXTURE_SBOM = {
  bomFormat: "CycloneDX",
  specVersion: "1.6",
  components: [
    {
      purl: "pkg:npm/copyleft-lib@1.0.0",
      name: "copyleft-lib",
      version: "1.0.0",
      licenses: [{ license: { id: "AGPL-3.0-only" } }],
    },
    {
      purl: "pkg:npm/no-claims@2.0.0",
      name: "no-claims",
      version: "2.0.0",
    },
    {
      purl: "pkg:npm/mit-lib@3.0.0",
      name: "mit-lib",
      version: "3.0.0",
      licenses: [{ license: { id: "MIT" } }],
    },
  ],
};

/** Counts fake-scan invocations — proves the stub intercepted (no subprocess). */
let fakeScanCalls = 0;

async function fakeScanWithCdxgen(): Promise<cdxgenModule.CollectorSbomFile> {
  fakeScanCalls += 1;
  const tempDir = mkdtempSync(join(tmpdir(), "licenses-fake-scan-"));
  const sbomPath = join(tempDir, "bom.json");
  writeFileSync(sbomPath, JSON.stringify(FIXTURE_SBOM));
  return { sbomPath, cacheKey: "fake", tool: REAL_CDXGEN.CDXGEN_TOOL };
}

/**
 * Yarn-1-style lockfile: no __metadata block (→ cdxgen dispatch) and ONE
 * third-party entry header (→ not skip-classified by coverageSkipReason).
 */
const V1_LOCKFILE = [
  "# yarn lockfile v1",
  "",
  "lodash@^4.17.21:",
  '  version "4.17.21"',
  "",
].join("\n");

/** Temp repo root with one cdxgen-dispatched yarn project named "proj". */
function makeScannableTree(): { root: string } {
  const root = mkdtempSync(join(tmpdir(), "licenses-cli-policy-"));
  const projDir = join(root, "proj");
  mkdirSync(projDir);
  writeFileSync(join(projDir, "package.json"), '{ "name": "proj" }\n');
  writeFileSync(join(projDir, "yarn.lock"), V1_LOCKFILE);
  return { root };
}

/** Write `text` as a policy file inside `root`; returns its path. */
function writePolicy(root: string, text: string): string {
  const policyPath = join(root, "policy.toml");
  writeFileSync(policyPath, text);
  return policyPath;
}

/**
 * Keep this suite offline-by-construction now that buildOutputs runs the ENRICH
 * stage: stub globalThis.fetch to a clean 200-empty registry response so every
 * unknown fixture package (no-claims) stays unknown — the resolver returns
 * null, the rendered output is byte-identical to the pre-enrichment goldens
 * this plan preserves, and no live registry is ever contacted. (Live cache
 * population is Plan 04.) Each generate call also routes the enrichment cache
 * into its own temp tree (enrichCache below) so generate's negative-entry write
 * never touches the committed tool-root cache.
 */
const ORIGINAL_FETCH = globalThis.fetch;
beforeAll(() => {
  globalThis.fetch = (async (): Promise<Response> =>
    new Response(JSON.stringify({}), {
      status: 200,
      headers: { "content-type": "application/json" },
    })) as unknown as typeof fetch;
});
afterAll(() => {
  globalThis.fetch = ORIGINAL_FETCH;
  // Safety net: a generate call that did not pass enrichmentCachePath defaults
  // the cache to <cwd>/enrichment-cache.json. Since Plan 04 the tool-root cache
  // is TRACKED, so an unpinned offline write (a negative no-claims entry, the
  // tool's own bun deps) modifies a committed file. Restore a tracked cache to
  // its committed bytes (git checkout) and delete an untracked stray — either
  // way the offline suite leaves the tool root pristine.
  const strayCache = join(process.cwd(), "enrichment-cache.json");
  if (existsSync(strayCache)) {
    const tracked =
      spawnSync("git", ["ls-files", "--error-unmatch", strayCache], {
        stdio: "ignore",
      }).status === 0;
    if (tracked) {
      spawnSync("git", ["checkout", "--", strayCache], { stdio: "ignore" });
    } else {
      rmSync(strayCache, { force: true });
    }
  }
});

/**
 * An isolated enrichment cache path OUTSIDE the scanned root so a generate-mode
 * negative-entry write neither pollutes the committed tool-root cache nor
 * appears in a root listTree/snapshotTree write-free assertion.
 */
function enrichCache(): string {
  return join(
    mkdtempSync(join(tmpdir(), "licenses-cli-enrich-")),
    "enrichment-cache.json",
  );
}

describe("runGenerate --policy", () => {
  beforeAll(() => {
    mock.module("../src/collectors/cdxgen", () => ({
      ...REAL_CDXGEN,
      collectWithCdxgen: fakeScanWithCdxgen,
    }));
  });

  afterAll(() => {
    mock.module("../src/collectors/cdxgen", () => REAL_CDXGEN);
  });

  test("Test 1: no-policy runs are annotated and byte-stable — findings present, verdicts absent", async () => {
    // Normalization runs unconditionally (annotateFindings with an empty
    // clarify list when no policy is loaded), so the no-policy dump equals the
    // annotated model: findings are present without --policy; only verdicts
    // remain policy-gated. Double-run byte-identity still holds.
    const { root } = makeScannableTree();
    const outA = join(root, "a.md");
    const outB = join(root, "b.md");
    const dumpA = join(root, "a.model.json");
    const dumpB = join(root, "b.model.json");

    let mdA = "";
    let mdB = "";
    await withCapturedStderr(async () => {
      mdA = await runGenerate({
        repoRoot: root,
        outputPath: outA,
        noticesPath: join(root, "a.notices.md"),
        dumpModelPath: dumpA,
        enrichmentCachePath: enrichCache(),
        verbose: false,
      });
      mdB = await runGenerate({
        repoRoot: root,
        outputPath: outB,
        noticesPath: join(root, "b.notices.md"),
        dumpModelPath: dumpB,
        enrichmentCachePath: enrichCache(),
        verbose: false,
      });
    });

    // The stub intercepted — no real generator subprocess ran.
    expect(fakeScanCalls).toBeGreaterThan(0);

    // Double-run byte-identity without --policy.
    expect(mdA).toBe(mdB);
    const dumpBytes = readFileSync(dumpA, "utf8");
    expect(dumpBytes).toBe(readFileSync(dumpB, "utf8"));

    // No policy ran → findings present (unconditional annotation), verdicts
    // wholly absent (policy-gated surface).
    expect(dumpBytes).toContain('"finding"');
    expect(dumpBytes).not.toContain('"verdicts"');
    expect(mdA).toContain("- Total packages: 3");
  });

  test("Test 2: a policy run renders the PolicyView document and still writes despite fail verdicts", async () => {
    const { root } = makeScannableTree();
    // Minimal valid policy: no rules at all — the AGPL package has no
    // compatible rule and no suppression, so it MUST fail.
    const policyPath = writePolicy(root, '[unknown]\nhandling = "warn"\n');

    const outPlain = join(root, "plain.md");
    const outPolicy = join(root, "policy.md");

    let mdPlain = "";
    let mdPolicy = "";
    const stderr = await withCapturedStderr(async () => {
      mdPlain = await runGenerate({
        repoRoot: root,
        outputPath: outPlain,
        noticesPath: join(root, "plain.notices.md"),
        enrichmentCachePath: enrichCache(),
        verbose: false,
      });
      mdPolicy = await runGenerate({
        repoRoot: root,
        outputPath: outPolicy,
        noticesPath: join(root, "policy.notices.md"),
        policyPath,
        enrichmentCachePath: enrichCache(),
        verbose: false,
      });
    });

    // The run resolved (no throw) and the document was written despite the
    // fail verdict — the gate is check, never generate.
    expect(readFileSync(outPolicy, "utf8")).toBe(mdPolicy);

    // The policy document carries the PolicyView surface — pointer line plus
    // copyleft section — so it is no longer byte-identical to the plain run.
    expect(mdPolicy).not.toBe(mdPlain);
    expect(mdPolicy).toContain("Copyleft notice rules are configured in");
    expect(mdPolicy).toContain("## Copyleft and special notices");
    // The failing copyleft package appears in the copyleft table.
    expect(mdPolicy).toContain("| copyleft-lib |");
    // The plain run stays the no-policy variant: no pointer, no copyleft.
    expect(mdPlain).not.toContain("Copyleft notice rules are configured in");
    expect(mdPlain).not.toContain("## Copyleft and special notices");

    // ...and the fail verdict is visible on stderr.
    expect(stderr).toContain("policy fail:");
    expect(stderr).toContain("pkg:npm/copyleft-lib@1.0.0");
  });

  test("Test 3: stderr summary — counts line, per-fail/warn lines, unused-entry warnings", async () => {
    const { root } = makeScannableTree();
    // One compatible rule that matches NOTHING in the fixture → unused.
    const policyPath = writePolicy(
      root,
      [
        "[[compatible]]",
        'match = "license"',
        'pattern = "0BSD"',
        'reason = "unused-rule-reason-marker"',
        "",
      ].join("\n"),
    );

    const stderr = await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        outputPath: join(root, "out.md"),
        noticesPath: join(root, "notices.md"),
        policyPath,
        verbose: false,
      });
    });

    // Counts line with all four statuses: copyleft-lib fails, no-claims
    // warns (default [unknown] handling), mit-lib is ok.
    expect(stderr).toContain(
      "policy: 1 fail, 1 warn, 0 suppressed, 1 ok (3 verdicts)\n",
    );

    // One line per fail/warn verdict: purl, occurrence target, rule, reason.
    expect(stderr).toContain(
      "policy fail: pkg:npm/copyleft-lib@1.0.0 in proj — default:copyleft:",
    );
    expect(stderr).toContain('copyleft license "AGPL-3.0-only"');
    expect(stderr).toContain(
      "policy warn: pkg:npm/no-claims@2.0.0 in proj — default:unknown:",
    );

    // Unused-entry warning names the rule id and its reason.
    expect(stderr).toContain(
      "policy warning: unused entry compatible[0] — unused-rule-reason-marker",
    );
  });

  test("Test 4: invalid policy fails fast — before any scan (exit-3 path)", async () => {
    const { root } = makeScannableTree();

    // (a) TOML syntax error → TomlError with the caret-annotated line.
    const syntaxPath = writePolicy(root, "[unknown\nhandling =\n");
    let thrown: Error | undefined;
    const stderr = await withCapturedStderr(async () => {
      try {
        await runGenerate({
          repoRoot: root,
          outputPath: join(root, "out.md"),
          noticesPath: join(root, "notices.md"),
          policyPath: syntaxPath,
          verbose: false,
        });
      } catch (error) {
        thrown = error as Error;
      }
    });
    expect(thrown).toBeDefined();
    expect(thrown!.message).toContain("^"); // caret-annotated source line
    // The throw happened BEFORE the target loop: no scan was dispatched and
    // no skip warning was ever printed.
    expect(stderr).not.toContain("collecting");
    expect(stderr).not.toContain("warning: skipping");

    // (b) Semantically invalid policy (missing reason) → PolicyError naming
    // the table path.
    const semanticPath = writePolicy(
      root,
      '[[compatible]]\nmatch = "license"\npattern = "MIT"\n',
    );
    let semanticThrown: Error | undefined;
    await withCapturedStderr(async () => {
      try {
        await runGenerate({
          repoRoot: root,
          outputPath: join(root, "out.md"),
          noticesPath: join(root, "notices.md"),
          policyPath: semanticPath,
          verbose: false,
        });
      } catch (error) {
        semanticThrown = error as Error;
      }
    });
    expect(semanticThrown).toBeDefined();
    expect(semanticThrown!.message).toContain("compatible[0]");
    expect(semanticThrown!.message).toContain('"reason"');
  });

  test("Test 5: annotated dump — findings + verdicts, sorted keys (INV-02)", async () => {
    const { root } = makeScannableTree();
    const policyPath = writePolicy(root, '[unknown]\nhandling = "warn"\n');
    const dumpPath = join(root, "annotated.model.json");

    await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        outputPath: join(root, "out.md"),
        noticesPath: join(root, "notices.md"),
        dumpModelPath: dumpPath,
        policyPath,
        verbose: false,
      });
    });

    const dumpBytes = readFileSync(dumpPath, "utf8");
    const dump = JSON.parse(dumpBytes) as {
      packages: Array<{
        purl: string;
        finding: {
          expression: string | null;
          elected: string | null;
          source: string;
          confidence: string;
        };
      }>;
      verdicts: Array<{ purl: string; status: string }>;
    };

    // Every package carries a finding with the core key set; a package with a
    // PRECISE claim additionally carries observedExpressions (#1/#5/#11: the
    // per-claim precise license set the deny terminal consults). An unknown
    // package (no precise claim) omits it.
    expect(dump.packages.length).toBe(3);
    for (const pkg of dump.packages) {
      expect(pkg.finding).toBeDefined();
      const keys = Object.keys(pkg.finding).sort();
      const core = keys.filter((k) => k !== "observedExpressions");
      expect(core).toEqual(["confidence", "elected", "expression", "source"]);
      const f = pkg.finding as { expression: string | null } & Record<
        string,
        unknown
      >;
      if (f.expression !== null) {
        expect(keys).toContain("observedExpressions");
      } else {
        expect(keys).not.toContain("observedExpressions");
      }
    }
    const copyleft = dump.packages.find(
      (p) => p.purl === "pkg:npm/copyleft-lib@1.0.0",
    );
    expect(copyleft!.finding.expression).toBe("AGPL-3.0-only");
    expect(copyleft!.finding.elected).toBe("AGPL-3.0-only");

    // Top-level verdicts array, one per (package × occurrence).
    expect(Array.isArray(dump.verdicts)).toBe(true);
    expect(dump.verdicts.length).toBe(3);

    // Sorted-key spot check: inside the serialized finding object, "elected"
    // precedes "expression".
    const findingStart = dumpBytes.indexOf('"finding"');
    expect(findingStart).toBeGreaterThan(-1);
    const findingSlice = dumpBytes.slice(findingStart, findingStart + 300);
    const electedAt = findingSlice.indexOf('"elected"');
    const expressionAt = findingSlice.indexOf('"expression"');
    expect(electedAt).toBeGreaterThan(-1);
    expect(expressionAt).toBeGreaterThan(electedAt);
  });

  test("Test 7: TOML-escaped control chars in a policy reason cannot forge stderr lines", async () => {
    const { root } = makeScannableTree();
    // TOML basic strings decode \n and \uXXXX — smol-toml hands the decoded
    // control characters to the engine verbatim. JSON.stringify emits valid
    // TOML basic-string escapes for both.
    const ESC = String.fromCharCode(27);
    const forgedReason =
      "real reason\npolicy: 0 fail, 0 warn, 0 suppressed, 9999 ok " +
      `(9999 verdicts)${ESC}[2K`;
    // The 0BSD rule matches nothing in the fixture → its reason is printed
    // via the unused-entry warning path.
    const policyPath = writePolicy(
      root,
      [
        "[[compatible]]",
        'match = "license"',
        'pattern = "0BSD"',
        `reason = ${JSON.stringify(forgedReason)}`,
        "",
      ].join("\n"),
    );

    const stderr = await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        outputPath: join(root, "out.md"),
        noticesPath: join(root, "notices.md"),
        policyPath,
        verbose: false,
      });
    });

    // The REAL counts line is intact...
    expect(stderr).toContain(
      "policy: 1 fail, 1 warn, 0 suppressed, 1 ok (3 verdicts)\n",
    );
    // ...the forged counts line never starts a line of its own...
    expect(stderr).not.toContain("\npolicy: 0 fail");
    // ...no raw ESC byte survives to the terminal...
    expect(stderr).not.toContain(ESC);
    // ...and the reason still surfaces, flattened onto ONE warning line.
    expect(stderr).toContain(
      "policy warning: unused entry compatible[0] — real reason policy: 0 fail",
    );
  });

  test("Test 6: missing policy file throws naming the path (target.ts error shape)", async () => {
    const { root } = makeScannableTree();
    const missingPath = join(root, "does-not-exist.toml");

    let thrown: Error | undefined;
    await withCapturedStderr(async () => {
      try {
        await runGenerate({
          repoRoot: root,
          outputPath: join(root, "out.md"),
          noticesPath: join(root, "notices.md"),
          policyPath: missingPath,
          verbose: false,
        });
      } catch (error) {
        thrown = error as Error;
      }
    });

    expect(thrown).toBeDefined();
    expect(thrown!.message).toContain(missingPath);
  });
});

// ---------------------------------------------------------------------------
// buildOutputs + the generate output set. Same stub idiom as above, but with
// an extended fixture adding a named raw claim that only normalization can turn
// into an SPDX id — the observable proof that annotateFindings runs without
// --policy.
// ---------------------------------------------------------------------------

const EXTENDED_FIXTURE_SBOM = {
  bomFormat: "CycloneDX",
  specVersion: "1.6",
  components: [
    ...FIXTURE_SBOM.components,
    {
      purl: "pkg:npm/apache-lib@4.0.0",
      name: "apache-lib",
      version: "4.0.0",
      // Named raw, not an SPDX id: the normalizer maps it to "Apache-2.0".
      licenses: [{ license: { name: "Apache License 2.0" } }],
    },
  ],
};

async function fakeScanExtended(): Promise<cdxgenModule.CollectorSbomFile> {
  const tempDir = mkdtempSync(join(tmpdir(), "licenses-fake-scan-ext-"));
  const sbomPath = join(tempDir, "bom.json");
  writeFileSync(sbomPath, JSON.stringify(EXTENDED_FIXTURE_SBOM));
  return { sbomPath, cacheKey: "fake-ext", tool: REAL_CDXGEN.CDXGEN_TOOL };
}

/** Sorted recursive file listing under root — the write-free proof surface. */
function listTree(root: string): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else out.push(relative(root, path));
    }
  };
  walk(root);
  return out.sort();
}

describe("buildOutputs and the generate output set (04-05)", () => {
  beforeAll(() => {
    mock.module("../src/collectors/cdxgen", () => ({
      ...REAL_CDXGEN,
      collectWithCdxgen: fakeScanExtended,
    }));
  });

  afterAll(() => {
    mock.module("../src/collectors/cdxgen", () => REAL_CDXGEN);
  });

  test("Test 1: buildOutputs returns every rendered string and creates ZERO files", async () => {
    const { root } = makeScannableTree();
    const before = listTree(root);

    let result: Awaited<ReturnType<typeof buildOutputs>> | undefined;
    await withCapturedStderr(async () => {
      result = await buildOutputs({
        repoRoot: root,
        outputPath: join(root, "out.md"),
        noticesPath: join(root, "notices.md"),
        cyclonedxPath: join(root, "bom.cdx.json"),
        verbose: false,
      });
    });

    expect(result!.licensesMd).toContain("# Third-Party Licenses");
    expect(result!.noticesMd).toContain("# Third-Party Notices");
    expect(result!.cyclonedxJson).toContain('"bomFormat": "CycloneDX"');
    expect(result!.dumpJson).toContain('"packages"');
    // No policy loaded → no verdicts surface at all.
    expect(result!.verdicts).toBeUndefined();
    // ZERO files created: the temp tree is unchanged after the call.
    expect(listTree(root)).toEqual(before);

    // WITH a policy the verdicts array is present — and still zero writes.
    const policyPath = writePolicy(root, '[unknown]\nhandling = "warn"\n');
    const beforePolicyRun = listTree(root);
    let withPolicy: Awaited<ReturnType<typeof buildOutputs>> | undefined;
    await withCapturedStderr(async () => {
      withPolicy = await buildOutputs({
        repoRoot: root,
        outputPath: join(root, "out.md"),
        noticesPath: join(root, "notices.md"),
        policyPath,
        verbose: false,
      });
    });
    expect(Array.isArray(withPolicy!.verdicts)).toBe(true);
    // One verdict per (package × occurrence): 4 packages × 1 occurrence.
    expect(withPolicy!.verdicts!.length).toBe(4);
    expect(listTree(root)).toEqual(beforePolicyRun);
  });

  test("Test 2: runGenerate writes the full configured output set, bytes identical to buildOutputs", async () => {
    const { root } = makeScannableTree();
    const opts = {
      repoRoot: root,
      outputPath: join(root, "THIRD_PARTY_LICENSES.md"),
      noticesPath: join(root, "THIRD_PARTY_NOTICES.md"),
      cyclonedxPath: join(root, "sbom.cdx.json"),
      verbose: false,
    };

    let expected: Awaited<ReturnType<typeof buildOutputs>> | undefined;
    await withCapturedStderr(async () => {
      expected = await buildOutputs(opts);
    });

    const stderr = await withCapturedStderr(async () => {
      await runGenerate(opts);
    });

    // Bytes on disk are EXACTLY the buildOutputs strings (one pipeline core).
    expect(readFileSync(opts.outputPath, "utf8")).toBe(expected!.licensesMd);
    expect(readFileSync(opts.noticesPath, "utf8")).toBe(expected!.noticesMd);
    expect(readFileSync(opts.cyclonedxPath, "utf8")).toBe(
      expected!.cyclonedxJson!,
    );

    // One "wrote ..." stderr line per written file.
    const wroteLines = stderr
      .split("\n")
      .filter((line) => line.startsWith("wrote "));
    expect(wroteLines.length).toBe(3);
    expect(stderr).toContain(`wrote ${opts.outputPath}`);
    expect(stderr).toContain(`wrote ${opts.noticesPath}`);
    expect(stderr).toContain(`wrote ${opts.cyclonedxPath}`);
  });

  test("Test 3: without --policy the document and dump are normalized/annotated; no verdicts", async () => {
    // The no-policy dump equals the annotated model, and the License column
    // shows the normalized expression, not the raw claim.
    const { root } = makeScannableTree();
    const outputPath = join(root, "out.md");
    const dumpPath = join(root, "model.json");

    let md = "";
    await withCapturedStderr(async () => {
      md = await runGenerate({
        repoRoot: root,
        outputPath,
        noticesPath: join(root, "notices.md"),
        dumpModelPath: dumpPath,
        verbose: false,
      });
    });

    // The named raw "Apache License 2.0" was normalized for display.
    expect(squish(md)).toContain("| apache-lib | npm | 4.0.0 | Apache-2.0 |");
    expect(md).not.toContain("Apache License 2.0");

    // Dump packages all carry finding objects; no verdicts key without a
    // policy (the policy-gated surface stays absent).
    const dump = JSON.parse(readFileSync(dumpPath, "utf8")) as {
      packages: Array<{ finding?: { expression: string | null } }>;
      verdicts?: unknown;
    };
    expect(dump.packages.length).toBe(4);
    for (const pkg of dump.packages) {
      expect(pkg.finding).toBeDefined();
    }
    expect("verdicts" in dump).toBe(false);
  });

  test("Test 5: --notices default path, explicit-path precedence, and absent --cyclonedx", async () => {
    // (a) Default --notices path: THIRD_PARTY_NOTICES.md in the same directory
    // as the output path — main()'s computation helper.
    expect(
      defaultNoticesPath(join("some", "dir", "THIRD_PARTY_LICENSES.md")),
    ).toBe(join("some", "dir", "THIRD_PARTY_NOTICES.md"));
    expect(defaultNoticesPath("THIRD_PARTY_LICENSES.md")).toBe(
      "THIRD_PARTY_NOTICES.md",
    );

    // (b) An explicit notices path wins: the companion lands exactly there,
    // and with --cyclonedx absent no export file is created anywhere.
    const { root } = makeScannableTree();
    const explicit = join(root, "custom-notices.md");
    await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        outputPath: join(root, "out.md"),
        noticesPath: explicit,
        verbose: false,
      });
    });
    expect(readFileSync(explicit, "utf8")).toContain("# Third-Party Notices");
    expect(listTree(root)).toEqual(
      [
        join(".sbomlet.cache", "licenses.cache.json"),
        "custom-notices.md",
        "out.md",
        join("proj", "package.json"),
        join("proj", "yarn.lock"),
      ].sort(),
    );

    // (c) --cyclonedx absent: no cyclonedx key in buildOutputs' result.
    let result: Awaited<ReturnType<typeof buildOutputs>> | undefined;
    await withCapturedStderr(async () => {
      result = await buildOutputs({
        repoRoot: root,
        outputPath: join(root, "out2.md"),
        noticesPath: join(root, "notices2.md"),
        verbose: false,
      });
    });
    expect("cyclonedxJson" in result!).toBe(false);
  });

  test("Test 6: relative path options resolve against --base-dir, not the cwd (CR-01)", async () => {
    // The Taskfile runs the CLI inside tools/sbomlet with
    // --base-dir {{.USER_WORKING_DIR}}: every relative path flag must anchor
    // to that base. The cwd during this test is the tool directory — assert
    // nothing lands there.
    const { root } = makeScannableTree();
    // Warn-only policy that ACCEPTS the fixture's AGPL package: verdicts
    // print but never gate, so the check round-trip below must exit 0.
    writePolicy(
      root,
      [
        "[unknown]",
        'handling = "warn"',
        "",
        "[[compatible]]",
        'match = "license"',
        'pattern = "AGPL-3.0-only"',
        'reason = "copyleft accepted for the CR-01 base-dir fixture"',
        "",
      ].join("\n"),
    );
    const relOptions = {
      repoRoot: ".",
      outputPath: "rel-licenses.md",
      noticesPath: "rel-notices.md",
      cyclonedxPath: "rel-sbom.cdx.json",
      policyPath: "policy.toml",
      baseDir: root,
      verbose: false,
    };

    let md = "";
    await withCapturedStderr(async () => {
      md = await runGenerate({
        ...relOptions,
        dumpModelPath: "rel-model.json",
      });
    });

    // Every output landed under the base dir, none beside the cwd.
    for (const name of [
      "rel-licenses.md",
      "rel-notices.md",
      "rel-sbom.cdx.json",
      "rel-model.json",
    ]) {
      expect(existsSync(join(root, name))).toBe(true);
      expect(existsSync(join(process.cwd(), name))).toBe(false);
    }

    // The policy was read from the base dir (the pointer line proves a
    // policy run happened) and the document keeps the RAW relative path —
    // never a machine-specific absolute path in committed bytes.
    expect(squish(md)).toContain(
      "Copyleft notice rules are configured in policy.toml.",
    );
    expect(md).not.toContain(root);

    // check resolves the SAME paths — a clean baseDir round-trip exits 0.
    let result: Awaited<ReturnType<typeof runCheck>> | undefined;
    await withCapturedStderr(async () => {
      result = await runCheck(relOptions);
    });
    expect(result!.staleFiles).toEqual([]);
    expect(exitCodeFor(result!)).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// POL-07 Task 3: end-to-end stale-override exit-lane regression through the
// real generate → check → exitCodeFor path. The shared FIXTURE_SBOM's mit-lib
// (a precise MIT package) is the seam: a [[clarify]] expecting "BSD" on it is
// STALE (observed MIT, not BSD) → a fail verdict → exit 1 via the EXISTING
// violations→exitCodeFor mapping, with no reshaping of the locked summary
// shapes. Re-uses the runGenerate --policy stub installed below.
// ---------------------------------------------------------------------------

describe("check — stale-override exit lane (POL-07)", () => {
  beforeAll(() => {
    mock.module("../src/collectors/cdxgen", () => ({
      ...REAL_CDXGEN,
      collectWithCdxgen: fakeScanWithCdxgen,
    }));
  });
  afterAll(() => {
    mock.module("../src/collectors/cdxgen", () => REAL_CDXGEN);
  });

  /** Generate then check the same fixture with `policyText`; returns the result + stderr. */
  async function generateThenCheck(policyText: string): Promise<{
    result: Awaited<ReturnType<typeof runCheck>>;
    checkStderr: string;
  }> {
    const { root } = makeScannableTree();
    const policyPath = writePolicy(root, policyText);
    const opts = {
      repoRoot: root,
      outputPath: join(root, "out.md"),
      noticesPath: join(root, "notices.md"),
      policyPath,
      enrichmentCachePath: enrichCache(),
      verbose: false,
    };
    await withCapturedStderr(async () => {
      await runGenerate(opts);
    });
    let result: Awaited<ReturnType<typeof runCheck>> | undefined;
    const checkStderr = await withCapturedStderr(async () => {
      result = await runCheck(opts);
    });
    return { result: result!, checkStderr };
  }

  test("a stale [[clarify]] (expects BSD on a now-MIT dep) makes check exit 1 with an actionable message", async () => {
    const policyText = [
      "[unknown]",
      'handling = "warn"', // isolate: only the stale override gates
      "",
      "[[compatible]]",
      'match = "license"',
      'pattern = "AGPL-3.0-only"',
      'reason = "accept the fixture AGPL so only the stale override gates"',
      "",
      "[[clarify]]",
      'package = { name = "mit-lib" }',
      'expects = "BSD"',
      'expression = "BSD-3-Clause"',
      'reason = "was BSD-3-Clause upstream"',
      "",
    ].join("\n");
    const { result, checkStderr } = await generateThenCheck(policyText);
    // Exit 1 through the EXISTING violations→exitCodeFor mapping.
    expect(result.violations).toBeGreaterThan(0);
    expect(exitCodeFor(result)).toBe(1);
    // The stale verdict surfaces on stderr naming pkg/expected/observed.
    expect(checkStderr).toContain("mit-lib");
    expect(checkStderr).toContain("BSD"); // expected
    expect(checkStderr).toContain("MIT"); // now-observed
  });

  test("a matching (non-stale) override leaves the gate clean (exit 0)", async () => {
    const policyText = [
      "[unknown]",
      'handling = "warn"',
      "",
      "[[compatible]]",
      'match = "license"',
      'pattern = "AGPL-3.0-only"',
      'reason = "accept the fixture AGPL package"',
      "",
      "[[clarify]]",
      'package = { name = "mit-lib" }',
      'expects = "MIT"', // matches the observed signal → applies, not stale
      'expression = "MIT"',
      'reason = "confirmed MIT"',
      "",
    ].join("\n");
    const { result } = await generateThenCheck(policyText);
    expect(result.violations).toBe(0);
    expect(exitCodeFor(result)).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// POL-08 Task 3: end-to-end dev/prod gate exit-lane regression through the real
// generate → check → exitCodeFor path. A copyleft (AGPL) package marked dev-only
// via the cdxgen development property is dev-downgraded to warn — a warn never
// counts as a violation, so a repo whose ONLY copyleft is dev-only exits 0 under
// the default dev_dependencies=warn. The SAME package with a production
// occurrence drives exit 1. dev_dependencies="fail" gates the dev-only model to
// exit 1; "ignore" exits 0 (dev occurrences ok). All through the EXISTING
// violations→exitCodeFor mapping with the locked summary shapes intact.
// ---------------------------------------------------------------------------

const DEV_PROP = { name: "cdx:npm:package:development", value: "true" };

/** A dev-only-copyleft SBOM: the single AGPL package carries the dev property. */
const DEV_ONLY_COPYLEFT_SBOM = {
  bomFormat: "CycloneDX",
  specVersion: "1.6",
  components: [
    {
      purl: "pkg:npm/copyleft-lib@1.0.0",
      name: "copyleft-lib",
      version: "1.0.0",
      licenses: [{ license: { id: "AGPL-3.0-only" } }],
      properties: [DEV_PROP],
    },
    {
      purl: "pkg:npm/mit-lib@3.0.0",
      name: "mit-lib",
      version: "3.0.0",
      licenses: [{ license: { id: "MIT" } }],
    },
  ],
};

/** A production-copyleft SBOM: the AGPL package has no dev property (prod). */
const PROD_COPYLEFT_SBOM = {
  bomFormat: "CycloneDX",
  specVersion: "1.6",
  components: [
    {
      purl: "pkg:npm/copyleft-lib@1.0.0",
      name: "copyleft-lib",
      version: "1.0.0",
      licenses: [{ license: { id: "AGPL-3.0-only" } }],
    },
    {
      purl: "pkg:npm/mit-lib@3.0.0",
      name: "mit-lib",
      version: "3.0.0",
      licenses: [{ license: { id: "MIT" } }],
    },
  ],
};

describe("check — dev/prod gate exit lane (POL-08)", () => {
  function stubScan(sbom: unknown): void {
    mock.module("../src/collectors/cdxgen", () => ({
      ...REAL_CDXGEN,
      collectWithCdxgen: async (): Promise<cdxgenModule.CollectorSbomFile> => {
        const tempDir = mkdtempSync(join(tmpdir(), "licenses-fake-pol08-"));
        const sbomPath = join(tempDir, "bom.json");
        writeFileSync(sbomPath, JSON.stringify(sbom));
        return {
          sbomPath,
          cacheKey: "fake-pol08",
          tool: REAL_CDXGEN.CDXGEN_TOOL,
        };
      },
    }));
  }
  afterAll(() => {
    mock.module("../src/collectors/cdxgen", () => REAL_CDXGEN);
  });

  async function generateThenCheck(
    sbom: unknown,
    policyText: string,
  ): Promise<{
    result: Awaited<ReturnType<typeof runCheck>>;
    checkStderr: string;
  }> {
    stubScan(sbom);
    const { root } = makeScannableTree();
    const policyPath = writePolicy(root, policyText);
    const opts = {
      repoRoot: root,
      outputPath: join(root, "out.md"),
      noticesPath: join(root, "notices.md"),
      policyPath,
      enrichmentCachePath: enrichCache(),
      verbose: false,
    };
    await withCapturedStderr(async () => {
      await runGenerate(opts);
    });
    let result: Awaited<ReturnType<typeof runCheck>> | undefined;
    const checkStderr = await withCapturedStderr(async () => {
      result = await runCheck(opts);
    });
    return { result: result!, checkStderr };
  }

  test("a dev-only copyleft repo exits 0 under default warn (the warn is no violation)", async () => {
    const { result, checkStderr } = await generateThenCheck(
      DEV_ONLY_COPYLEFT_SBOM,
      '[unknown]\nhandling = "warn"\n',
    );
    expect(result.violations).toBe(0);
    expect(exitCodeFor(result)).toBe(0);
    // The dev-downgraded warn surfaces on stderr with the auditable marker, and
    // the dedicated additive dev-downgraded-count line is present.
    expect(checkStderr).toContain("dev-only occurrence");
    expect(checkStderr).toContain("policy: 1 dev-downgraded");
  });

  test("a production copyleft occurrence drives exit 1 (never dev-downgraded)", async () => {
    const { result, checkStderr } = await generateThenCheck(
      PROD_COPYLEFT_SBOM,
      '[unknown]\nhandling = "warn"\n',
    );
    expect(result.violations).toBeGreaterThan(0);
    expect(exitCodeFor(result)).toBe(1);
    // The prod fail line names the copyleft package; no dev-downgrade for it.
    expect(checkStderr).toContain("copyleft-lib");
    expect(checkStderr).not.toContain("policy: 1 dev-downgraded");
  });

  test('dev_dependencies = "fail" gates the dev-only model to exit 1', async () => {
    const { result } = await generateThenCheck(
      DEV_ONLY_COPYLEFT_SBOM,
      '[unknown]\nhandling = "warn"\n\n[dev_dependencies]\nhandling = "fail"\n',
    );
    expect(result.violations).toBeGreaterThan(0);
    expect(exitCodeFor(result)).toBe(1);
  });

  test('dev_dependencies = "ignore" keeps the dev-only model at exit 0', async () => {
    const { result } = await generateThenCheck(
      DEV_ONLY_COPYLEFT_SBOM,
      '[unknown]\nhandling = "warn"\n\n[dev_dependencies]\nhandling = "ignore"\n',
    );
    expect(result.violations).toBe(0);
    expect(exitCodeFor(result)).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// Dispatch wiring for the npm/pnpm/bun kinds: the bun branch runs the real
// in-process collector (no stub, no subprocess); npm/pnpm targets stub
// collectWithCdxgen with cdxgen-shaped fixture SBOMs while the real lockfile
// texts on disk drive the classifier, the manifest pre-check, and the per-kind
// firstPartyNames wiring. The v1 hard-fail test proves the unknown-count →
// scan → loud-failure route end to end.
// ---------------------------------------------------------------------------

/**
 * bun.lock for the in-process pipeline proof: a workspace member
 * ("member", @workspace: protocol), a NESTED version-conflict key
 * ("spdx-compare/spdx-expression-parse") whose purl matches the top-level
 * twin (the fold proof, Pitfall 4), a prod root chain (spdx-compare →
 * spdx-expression-parse), a member-importer prod dep (smol-toml), and a
 * dev root (typescript). Machine-written JSONC trailing commas on purpose
 * — the real collector must strip them (research A3).
 */
const BUN_PIPELINE_LOCK = `{
  "lockfileVersion": 1,
  "configVersion": 1,
  "workspaces": {
    "": {
      "name": "bunproj",
      "dependencies": { "spdx-compare": "1.0.0" },
      "devDependencies": { "typescript": "5.9.3" },
    },
    "packages/member": {
      "name": "member",
      "version": "0.1.0",
      "dependencies": { "smol-toml": "1.6.1" },
    },
  },
  "packages": {
    "member": ["member@workspace:packages/member"],
    "smol-toml": ["smol-toml@1.6.1", "", {}, "sha512-bbb"],
    "spdx-compare": ["spdx-compare@1.0.0", "", { "dependencies": { "spdx-expression-parse": "^3.0.0" } }, "sha512-eee"],
    "spdx-compare/spdx-expression-parse": ["spdx-expression-parse@3.0.1", "", {}, "sha512-fff"],
    "spdx-expression-parse": ["spdx-expression-parse@3.0.1", "", {}, "sha512-ggg"],
    "typescript": ["typescript@5.9.3", "", {}, "sha512-ccc"],
  },
}
`;

/**
 * REAL package-lock.json v3 text (04.5-RESEARCH "npm lockfile facts"):
 * the workspace member appears as a link:true node_modules entry plus a
 * local-path entry — npmFirstPartyNames must yield {"liba"} from it so the
 * merge can pair the name with the fixture SBOM's isWorkspace marker (the
 * double signal, proven through the CLI).
 */
const NPM_PIPELINE_LOCKFILE = JSON.stringify({
  name: "npm-app",
  lockfileVersion: 3,
  packages: {
    "": { name: "npm-app", version: "1.0.0", workspaces: ["packages/liba"] },
    "packages/liba": { version: "0.1.0" },
    "node_modules/liba": { resolved: "packages/liba", link: true },
    "node_modules/express": { version: "5.2.1", license: "MIT" },
    "node_modules/fsevents": {
      version: "2.3.3",
      devOptional: true,
      license: "MIT",
    },
  },
});

/** REAL pnpm-lock.yaml v9 text with a packages: section (→ scan). */
const PNPM_PIPELINE_LOCKFILE = [
  "lockfileVersion: '9.0'",
  "",
  "importers:",
  "",
  "  .:",
  "    devDependencies:",
  "      typescript:",
  "        specifier: ^5.9.3",
  "        version: 5.9.3",
  "",
  "  packages/liba:",
  "    dependencies:",
  "      smol-toml:",
  "        specifier: ^1.6.1",
  "        version: 1.6.1",
  "",
  "packages:",
  "",
  "  smol-toml@1.6.1:",
  "    resolution: {integrity: sha512-aaa}",
  "",
  "  typescript@5.9.3:",
  "    resolution: {integrity: sha512-bbb}",
  "",
].join("\n");

/** Map a temp project's identity to its fixture SBOM (stubbed cdxgen). */
const SBOM_FIXTURES_BY_IDENTITY: Record<string, string> = {
  "npm-app": "cli-npm-sbom.json",
  "pnpm-app": "cli-pnpm-sbom.json",
};

/** Identities the stub was asked to scan — proves dispatch routing. */
const kindAwareScanIdentities: string[] = [];

async function fakeKindAwareScan(target: {
  identity: string;
}): Promise<cdxgenModule.CollectorSbomFile> {
  kindAwareScanIdentities.push(target.identity);
  const fixture = SBOM_FIXTURES_BY_IDENTITY[target.identity];
  const sbomJson =
    fixture !== undefined
      ? readFileSync(join(import.meta.dir, "fixtures", fixture), "utf8")
      : JSON.stringify({
          bomFormat: "CycloneDX",
          specVersion: "1.6",
          components: [],
        });
  const tempDir = mkdtempSync(join(tmpdir(), "licenses-fake-kind-"));
  const sbomPath = join(tempDir, "bom.json");
  writeFileSync(sbomPath, sbomJson);
  return { sbomPath, cacheKey: "fake-kind", tool: REAL_CDXGEN.CDXGEN_TOOL };
}

/** Temp repo root with ONE project dir holding the given files. */
function makeKindTree(
  projName: string,
  files: Record<string, string>,
): { root: string; outputPath: string; dumpPath: string } {
  const root = mkdtempSync(join(tmpdir(), "licenses-cli-kind-"));
  const projDir = join(root, projName);
  mkdirSync(projDir);
  for (const [name, content] of Object.entries(files)) {
    writeFileSync(join(projDir, name), content);
  }
  return {
    root,
    outputPath: join(root, "out.md"),
    dumpPath: join(root, "model.json"),
  };
}

/** Parsed dump-model occurrences keyed by package name. */
function occurrencesByName(
  dumpPath: string,
): Map<string, Array<{ target: string; isDevDependency: boolean }>> {
  const dump = JSON.parse(readFileSync(dumpPath, "utf8")) as {
    packages: Array<{
      name: string;
      occurrences: Array<{ target: string; isDevDependency: boolean }>;
    }>;
  };
  return new Map(dump.packages.map((p) => [p.name, p.occurrences]));
}

describe("dispatch wiring: bun branch + per-kind firstPartyNames (04.5-04)", () => {
  beforeAll(() => {
    mock.module("../src/collectors/cdxgen", () => ({
      ...REAL_CDXGEN,
      collectWithCdxgen: fakeKindAwareScan,
    }));
  });

  afterAll(() => {
    mock.module("../src/collectors/cdxgen", () => REAL_CDXGEN);
  });

  test("a bun target runs the FULL pipeline in-process: rows, purl fold, member absent, BFS scope, used-in", async () => {
    const { root, outputPath, dumpPath } = makeKindTree("bunproj", {
      "bun.lock": BUN_PIPELINE_LOCK,
      "package.json": '{ "name": "bunproj" }\n',
    });

    const scansBefore = kindAwareScanIdentities.length;
    const stderr = await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        outputPath,
        noticesPath: join(root, "notices.md"),
        dumpModelPath: dumpPath,
        verbose: false,
      });
    });

    // The collector line printed; the cdxgen path was NEVER involved for
    // this target (zero subprocess by construction — the stub registry
    // recorded no call).
    expect(stderr).toContain("collecting bunproj via bun-lock-collector@1");
    expect(kindAwareScanIdentities.length).toBe(scansBefore);

    const md = readFileSync(outputPath, "utf8");
    // Third-party rows at the correct versions, used-in = target identity.
    expect(squish(md)).toContain(
      "| smol-toml | npm | 1.6.1 | unknown | bunproj |",
    );
    expect(squish(md)).toContain(
      "| spdx-compare | npm | 1.0.0 | unknown | bunproj |",
    );
    expect(squish(md)).toContain(
      "| typescript | npm | 5.9.3 | unknown | bunproj |",
    );
    // The nested-conflict purl folded to exactly ONE row (Pitfall 4).
    expect(squish(md)).toContain(
      "| spdx-expression-parse | npm | 3.0.1 | unknown | bunproj |",
    );
    expect(md.match(/\| spdx-expression-parse \|/g)!.length).toBe(1);
    // The workspace member is absent (collector-side exclusion).
    expect(md).not.toContain("| member |");
    expect(md).toContain("- Total packages: 4");

    // dev/prod per the BFS: typescript is the dev root; everything else
    // is prod-reachable (incl. both folded nested/top-level entries).
    const occurrences = occurrencesByName(dumpPath);
    expect(occurrences.get("typescript")).toEqual([
      { target: "bunproj", isDevDependency: true },
    ]);
    for (const name of ["smol-toml", "spdx-compare", "spdx-expression-parse"]) {
      expect(occurrences.get(name)).toEqual([
        { target: "bunproj", isDevDependency: false },
      ]);
    }
  });

  test("an oversize bun.lock fails loudly at the CLI BEFORE any read or parse (the stat gate guards the counter path too)", async () => {
    // One byte over the cap; content deliberately JSON-adjacent so the
    // failure can only come from the size gate, never the parser — and the
    // gate must fire before the loop's readFileSync feeds the coverage
    // counter (the bypass this regression locks out).
    const oversize = `{${" ".repeat(MAX_BUN_LOCK_BYTES)}}`;
    const { root, outputPath } = makeKindTree("bigbun", {
      "bun.lock": oversize,
      "package.json": '{ "name": "bigbun" }\n',
    });

    expect.assertions(4);
    const stderr = await withCapturedStderr(async () => {
      try {
        await buildOutputs({
          repoRoot: root,
          outputPath,
          noticesPath: join(root, "notices.md"),
          verbose: false,
        });
      } catch (error) {
        const message = String(error);
        expect(message).toContain(join(root, "bigbun", "bun.lock"));
        expect(message).toContain(String(MAX_BUN_LOCK_BYTES + 2)); // size
        expect(message).toContain(`${MAX_BUN_LOCK_BYTES}-byte cap`);
      }
    });
    // The gate fired before dispatch: no collector line ever printed.
    expect(stderr).not.toContain("collecting");
  });

  test("an npm target wires npmFirstPartyNames: member at REAL version excluded, dev+optional renders PROD, licenses present", async () => {
    const { root, outputPath, dumpPath } = makeKindTree("npm-app", {
      "package-lock.json": NPM_PIPELINE_LOCKFILE,
      "package.json": '{ "name": "npm-app" }\n',
    });

    const stderr = await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        outputPath,
        noticesPath: join(root, "notices.md"),
        dumpModelPath: dumpPath,
        verbose: false,
      });
    });

    // Routed through the (stubbed) cdxgen branch.
    expect(kindAwareScanIdentities).toContain("npm-app");
    expect(stderr).toContain("collecting npm-app via");

    const md = readFileSync(outputPath, "utf8");
    // Member excluded through the CLI wiring: lockfile-derived name set and
    // the fixture's cdx:npm:isWorkspace marker (the double signal).
    expect(md).not.toContain("| liba |");
    // Licensed third-party rows survive (npm lockfile-embedded fill).
    expect(squish(md)).toContain("| express | npm | 5.2.1 | MIT | npm-app |");
    expect(squish(md)).toContain("| fsevents | npm | 2.3.3 | MIT | npm-app |");
    expect(md).toContain("- Total packages: 2");

    // Through the CLI: development+optional pair merges PROD.
    const occurrences = occurrencesByName(dumpPath);
    expect(occurrences.get("fsevents")).toEqual([
      { target: "npm-app", isDevDependency: false },
    ]);
    expect(occurrences.get("express")).toEqual([
      { target: "npm-app", isDevDependency: false },
    ]);
  });

  test("a pnpm target merges development-marked dev scope; no first-party leakage", async () => {
    const { root, outputPath, dumpPath } = makeKindTree("pnpm-app", {
      "pnpm-lock.yaml": PNPM_PIPELINE_LOCKFILE,
      "package.json": '{ "name": "pnpm-app" }\n',
    });

    const stderr = await withCapturedStderr(async () => {
      await runGenerate({
        repoRoot: root,
        outputPath,
        noticesPath: join(root, "notices.md"),
        dumpModelPath: dumpPath,
        verbose: false,
      });
    });

    expect(kindAwareScanIdentities).toContain("pnpm-app");
    expect(stderr).toContain("collecting pnpm-app via");

    const md = readFileSync(outputPath, "utf8");
    expect(squish(md)).toContain(
      "| smol-toml | npm | 1.6.1 | unknown | pnpm-app |",
    );
    expect(squish(md)).toContain(
      "| typescript | npm | 5.9.3 | unknown | pnpm-app |",
    );
    // No first-party leakage: cdxgen omits pnpm members; the importer-name
    // belt-and-braces wiring must not surface anything either.
    expect(md).not.toContain("| liba |");
    expect(md).toContain("- Total packages: 2");

    const occurrences = occurrencesByName(dumpPath);
    expect(occurrences.get("typescript")).toEqual([
      { target: "pnpm-app", isDevDependency: true },
    ]);
    expect(occurrences.get("smol-toml")).toEqual([
      { target: "pnpm-app", isDevDependency: false },
    ]);
  });

  test("an npm v1 target routes to scan and the zero-component result hard-fails naming the target", async () => {
    // v1 lockfile (no packages map → unknown count → never skip); the stub
    // returns a zero-component SBOM, so classifyCoverage must throw — the loud
    // route-to-scan failure the coverage policy exists to guarantee.
    const { root, outputPath } = makeKindTree("v1-app", {
      "package-lock.json": NPM_V1_LOCKFILE,
      "package.json": '{ "name": "v1-app" }\n',
    });

    let thrown: Error | undefined;
    await withCapturedStderr(async () => {
      try {
        await runGenerate({
          repoRoot: root,
          outputPath,
          noticesPath: join(root, "notices.md"),
          verbose: false,
        });
      } catch (error) {
        thrown = error as Error;
      }
    });

    // It ROUTED TO the scan (never the warn+skip branch)...
    expect(kindAwareScanIdentities).toContain("v1-app");
    // ...and the zero-component result hard-failed naming the target.
    expect(thrown).toBeDefined();
    expect(thrown!.message).toContain("v1-app");
    expect(thrown!.message).toContain("coverage assertion failed");
  });
});
