import { describe, expect, test } from "bun:test";

import {
  ecosystemFor,
  isLockfileEmpty,
  manifestFilesFor,
  selectJsGenerator,
} from "../src/collectors/dispatch";

// Inline string fixtures — lockfile snippets are small and self-documenting.

const V8_LOCKFILE = [
  '# This file is generated by running "yarn install" inside your project.',
  "# Manual changes might be lost - proceed with caution!",
  "",
  "__metadata:",
  "  version: 8",
  "  cacheKey: 10c0",
  "",
  '"left-pad@npm:^1.3.0":',
  "  version: 1.3.0",
].join("\n");

const V9_LOCKFILE = ["__metadata:", "  version: 9", "  cacheKey: 11c0"].join(
  "\n",
);

const V6_LOCKFILE = [
  '# This file is generated by running "yarn install" inside your project.',
  "",
  "__metadata:",
  "  version: 6",
  "  cacheKey: 8",
].join("\n");

// No __metadata block at all; the first PACKAGE entry has an indented
// "version: 8" line that must NOT trigger plugin dispatch.
const PACKAGE_VERSION_8_NO_METADATA = [
  '"some-package@npm:^8.0.0":',
  "  version: 8",
  '  resolution: "some-package@npm:8.0.0"',
].join("\n");

describe("selectJsGenerator", () => {
  test("__metadata version 8 and 9 dispatch to yarn-plugin (rule is >= 8)", () => {
    expect(selectJsGenerator(V8_LOCKFILE)).toBe("yarn-plugin");
    expect(selectJsGenerator(V9_LOCKFILE)).toBe("yarn-plugin");
  });

  test("__metadata version 6 dispatches to cdxgen (plugin hard-fails on Yarn 3)", () => {
    expect(selectJsGenerator(V6_LOCKFILE)).toBe("cdxgen");
  });

  test("empty and whitespace-only lockfiles dispatch to cdxgen", () => {
    expect(selectJsGenerator("")).toBe("cdxgen");
    expect(selectJsGenerator("   \n\t\n  ")).toBe("cdxgen");
  });

  test("garbage text without a __metadata block dispatches to cdxgen, never throws", () => {
    expect(selectJsGenerator("not a lockfile at all }{ ::: %%%")).toBe(
      "cdxgen",
    );
    expect(selectJsGenerator("version: 8\nbut no metadata header")).toBe(
      "cdxgen",
    );
  });

  test("a package entry's version: 8 line without a __metadata block never triggers plugin dispatch", () => {
    expect(selectJsGenerator(PACKAGE_VERSION_8_NO_METADATA)).toBe("cdxgen");
  });
});

describe("isLockfileEmpty", () => {
  test("true for empty string and whitespace-only text", () => {
    expect(isLockfileEmpty("")).toBe(true);
    expect(isLockfileEmpty("  \n\t \n")).toBe(true);
  });

  test("false for any non-whitespace text", () => {
    expect(isLockfileEmpty("# comment only\n")).toBe(false);
    expect(isLockfileEmpty(V8_LOCKFILE)).toBe(false);
  });
});

describe("ecosystemFor / manifestFilesFor", () => {
  test("yarn maps to js with yarn.lock + package.json", () => {
    expect(ecosystemFor("yarn")).toBe("js");
    expect(manifestFilesFor("yarn")).toEqual(["yarn.lock", "package.json"]);
  });

  test("poetry maps to python with poetry.lock + pyproject.toml", () => {
    expect(ecosystemFor("poetry")).toBe("python");
    expect(manifestFilesFor("poetry")).toEqual([
      "poetry.lock",
      "pyproject.toml",
    ]);
  });

  test("uv maps to python with uv.lock + pyproject.toml", () => {
    expect(ecosystemFor("uv")).toBe("python");
    expect(manifestFilesFor("uv")).toEqual(["uv.lock", "pyproject.toml"]);
  });

  test("npm maps to js with package-lock.json + package.json", () => {
    expect(ecosystemFor("npm")).toBe("js");
    expect(manifestFilesFor("npm")).toEqual([
      "package-lock.json",
      "package.json",
    ]);
  });

  test("pnpm maps to js with pnpm-lock.yaml + package.json — pnpm-workspace.yaml deliberately NOT hashed", () => {
    expect(ecosystemFor("pnpm")).toBe("js");
    expect(manifestFilesFor("pnpm")).toEqual([
      "pnpm-lock.yaml",
      "package.json",
    ]);
  });

  test("bun maps to js with bun.lock + package.json", () => {
    expect(ecosystemFor("bun")).toBe("js");
    expect(manifestFilesFor("bun")).toEqual(["bun.lock", "package.json"]);
  });

  test("nuget has no cdxgen ecosystem (in-process collection) and hashes ONLY the lock", () => {
    expect(() => ecosystemFor("nuget")).toThrow(
      "nuget targets are collected in-process and have no cdxgen ecosystem",
    );
    expect(manifestFilesFor("nuget")).toEqual(["packages.lock.json"]);
  });
});
