import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, test } from "bun:test";

import {
  firstPartyNames,
  npmFirstPartyNames,
  npmThirdPartyEntryCount,
  nugetThirdPartyEntryCount,
  pnpmImporterNames,
  pnpmThirdPartyEntryCount,
  pythonThirdPartyEntryCount,
  thirdPartyEntryCount,
  yarnWorkspaceMembers,
} from "../src/targets/firstParty";

describe("firstPartyNames — workspace/portal member set from lockfile text", () => {
  test("verified real-world portal and workspace entry headers yield their names", () => {
    // Both line shapes verified in frontend/yarn.lock (02-RESEARCH Pattern 3),
    // including the ::locator suffix on portal resolutions.
    const lockfile = [
      '"iframe-rpc-react@portal:../libraries/iframe-rpc-react::locator=myapp%40workspace%3A.":',
      "  version: 0.0.0-use.local",
      '"myapp@workspace:.":',
      "  version: 0.0.0-use.local",
    ].join("\n");

    expect(firstPartyNames(lockfile)).toEqual(
      new Set(["iframe-rpc-react", "myapp"]),
    );
  });

  test("scoped names capture the full @scope/name (lazy match does not stop at the leading @)", () => {
    const lockfile =
      '"@scratch/foo@workspace:apps/x":\n  version: 0.0.0-use.local\n';

    expect(firstPartyNames(lockfile)).toEqual(new Set(["@scratch/foo"]));
  });

  test("comma-separated descriptor headers test each descriptor, not just the line start", () => {
    const lockfile =
      '"iframe-rpc@npm:^1.0.0, iframe-rpc@portal:../libraries/iframe-rpc":\n' +
      "  version: 0.0.0-use.local\n";

    expect(firstPartyNames(lockfile)).toEqual(new Set(["iframe-rpc"]));
  });

  test("indented body lines and @npm:-only entries contribute nothing", () => {
    const lockfile = [
      '"lodash@npm:^4.17.21":',
      "  version: 4.17.21",
      '  resolution: "lodash@npm:4.17.21"',
      "  version: 0.0.0-use.local", // body line that LOOKS first-party-ish
      "semver@npm:^7.6.0:",
      "  version: 7.7.1",
      "",
    ].join("\n");

    expect(firstPartyNames(lockfile)).toEqual(new Set());
  });
});

describe("thirdPartyEntryCount — non-workspace/portal entry headers", () => {
  test("a zero-dependency Yarn-4 lockfile (__metadata + workspace self-entry) counts 0", () => {
    const lockfile = [
      '# This file is generated by running "yarn install" inside your project.',
      "# Manual changes might be lost - proceed with caution!",
      "",
      "__metadata:",
      "  version: 8",
      "  cacheKey: 10c0",
      "",
      '"proj@workspace:.":',
      "  version: 0.0.0-use.local",
      "  languageName: unknown",
      "  linkType: soft",
      "",
    ].join("\n");

    expect(thirdPartyEntryCount(lockfile)).toBe(0);
  });

  test("npm entries count; workspace/portal/__metadata headers and body lines do not", () => {
    const lockfile = [
      "__metadata:",
      "  version: 8",
      '"lodash@npm:^4.17.21":',
      "  version: 4.17.21",
      '"myapp@workspace:.":',
      "  version: 0.0.0-use.local",
      '"iframe-rpc-react@portal:../libraries/iframe-rpc-react::locator=myapp%40workspace%3A.":',
      "  version: 0.0.0-use.local",
      "semver@npm:^7.6.0:",
      "  version: 7.7.1",
    ].join("\n");

    expect(thirdPartyEntryCount(lockfile)).toBe(2);
  });

  test("a header with ANY workspace/portal descriptor resolves first-party and is not counted", () => {
    const lockfile =
      '"iframe-rpc@npm:^1.0.0, iframe-rpc@portal:../libraries/iframe-rpc":\n' +
      "  version: 0.0.0-use.local\n";

    expect(thirdPartyEntryCount(lockfile)).toBe(0);
  });

  test("a comment-only Yarn-1 placeholder lockfile counts 0 (genuinely zero entries)", () => {
    const lockfile =
      "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n" +
      "# yarn lockfile v1\n";

    expect(thirdPartyEntryCount(lockfile)).toBe(0);
  });

  test("Yarn-1 entry headers (no resolution protocol) count as third-party", () => {
    const lockfile = [
      "# yarn lockfile v1",
      "",
      "lodash@^4.17.21:",
      '  version "4.17.21"',
      '"@babel/code-frame@^7.0.0":',
      '  version "7.26.2"',
    ].join("\n");

    expect(thirdPartyEntryCount(lockfile)).toBe(2);
  });
});

describe("pythonThirdPartyEntryCount — poetry/uv [[package]] tables", () => {
  test("a dependency-free poetry.lock (metadata block only, no packages) counts 0", () => {
    const lockfile = [
      "# This file is automatically @generated by Poetry 2.1.1 and should not be changed by hand.",
      "",
      "[metadata]",
      'lock-version = "2.1"',
      'python-versions = ">=3.12"',
      'content-hash = "abc123"',
      "",
    ].join("\n");

    expect(pythonThirdPartyEntryCount(lockfile)).toBe(0);
  });

  test("poetry [[package]] tables count as third-party (poetry never lists the root project)", () => {
    const lockfile = [
      "[[package]]",
      'name = "anyio"',
      'version = "4.8.0"',
      "",
      "[[package]]",
      'name = "attrs"',
      'version = "25.1.0"',
      "",
      "[metadata]",
      'lock-version = "2.1"',
    ].join("\n");

    expect(pythonThirdPartyEntryCount(lockfile)).toBe(2);
  });

  test("a dependency-free uv.lock (only the project's own virtual self entry) counts 0", () => {
    const lockfile = [
      "version = 1",
      'requires-python = ">=3.12"',
      "",
      "[[package]]",
      'name = "myproject"',
      'version = "0.1.0"',
      'source = { virtual = "." }',
      "",
    ].join("\n");

    expect(pythonThirdPartyEntryCount(lockfile)).toBe(0);
  });

  test("uv editable workspace members are first-party; registry packages count", () => {
    const lockfile = [
      "version = 1",
      "",
      "[[package]]",
      'name = "myproject"',
      'version = "0.1.0"',
      'source = { editable = "." }',
      "",
      "[[package]]",
      'name = "member"',
      'version = "0.2.0"',
      'source = { editable = "packages/member" }',
      "",
      "[[package]]",
      'name = "idna"',
      'version = "3.10"',
      'source = { registry = "https://pypi.org/simple" }',
      "",
    ].join("\n");

    expect(pythonThirdPartyEntryCount(lockfile)).toBe(1);
  });

  test("garbage and sub-table lines never throw and contribute nothing", () => {
    expect(pythonThirdPartyEntryCount("")).toBe(0);
    expect(pythonThirdPartyEntryCount("not toml at all\n{{{}}}\n")).toBe(0);
    // [package.source] sub-tables (poetry directory deps) do NOT mark the
    // entry local — conservative: the target still gets scanned.
    const lockfile = [
      "[[package]]",
      'name = "local-dep"',
      'version = "0.1.0"',
      "",
      "[package.source]",
      'type = "directory"',
      'url = "../local-dep"',
    ].join("\n");
    expect(pythonThirdPartyEntryCount(lockfile)).toBe(1);
  });
});

// npm v3 fixture — every entry shape cited from 04.5-RESEARCH "npm lockfile
// facts the counters rely on" (verified against a real package-lock.json v3
// and the npm-workspaces fixture generated in the 04.5 spike).
const NPM_V3_LOCKFILE = JSON.stringify({
  name: "fixture",
  lockfileVersion: 3,
  packages: {
    "": { name: "fixture", version: "1.0.0" },
    "node_modules/express": { version: "5.2.1", license: "MIT" },
    "node_modules/typescript": { version: "5.9.3", dev: true },
    "node_modules/ts-node": { version: "10.9.2", devOptional: true },
    "node_modules/pg-cloudflare": { version: "1.1.1", optional: true },
    "node_modules/liba": { resolved: "packages/liba", link: true },
    "packages/liba": { name: "liba", version: "0.1.0" },
  },
});

describe("npmThirdPartyEntryCount — node_modules entries with link !== true", () => {
  test("v3 lockfile counts node_modules keys excluding link:true workspace entries", () => {
    // 5 node_modules keys, one of which is link:true → 4 third-party.
    expect(npmThirdPartyEntryCount(NPM_V3_LOCKFILE)).toBe(4);
  });

  test('packages present but only the root "" entry → 0 (positively-determined zero, warn+skip branch)', () => {
    const lockfile = JSON.stringify({
      name: "fixture",
      lockfileVersion: 3,
      packages: { "": { name: "fixture", version: "1.0.0" } },
    });

    expect(npmThirdPartyEntryCount(lockfile)).toBe(0);
  });

  test("v1 lockfile (no packages key) → undefined, NOT 0 (Pitfall 6: route to scan)", () => {
    const v1 = JSON.stringify({
      name: "fixture",
      lockfileVersion: 1,
      dependencies: { lodash: { version: "4.17.21" } },
    });

    expect(npmThirdPartyEntryCount(v1)).toBeUndefined();
  });

  test("garbage, non-JSON, and empty-object JSON → undefined, never throws", () => {
    expect(npmThirdPartyEntryCount("not json at all }{")).toBeUndefined();
    expect(npmThirdPartyEntryCount("")).toBeUndefined();
    expect(npmThirdPartyEntryCount("{}")).toBeUndefined();
    // packages key present but not an object → still unknown.
    expect(npmThirdPartyEntryCount('{"packages": 42}')).toBeUndefined();
    expect(npmThirdPartyEntryCount('"just a string"')).toBeUndefined();
  });
});

// nuget fixtures — the 15-01 collector-fixture shapes (v1 net9.0 section with
// Direct + Transitive entries; v2 CPM section with a type=Project reference).
const NUGET_V1_LOCK = JSON.stringify({
  version: 1,
  dependencies: {
    "net9.0": {
      "Newtonsoft.Json": {
        type: "Direct",
        requested: "[13.0.4, )",
        resolved: "13.0.4",
      },
      Serilog: { type: "Direct", requested: "[4.3.1, )", resolved: "4.3.1" },
      "Microsoft.NETCore.Platforms": { type: "Transitive", resolved: "1.1.0" },
      "runtime.native.System": { type: "Transitive", resolved: "4.3.0" },
    },
  },
});

const NUGET_CPM_LOCK = JSON.stringify({
  version: 2,
  dependencies: {
    "net9.0": {
      "Microsoft.Extensions.Logging": { type: "Direct", resolved: "9.0.9" },
      "Some.Transitive": { type: "CentralTransitive", resolved: "9.0.9" },
      "fixture.lib": { type: "Project" },
    },
  },
});

describe("nugetThirdPartyEntryCount — entries with type !== 'Project' across all sections", () => {
  test("the v1 fixture counts its non-Project entries", () => {
    expect(nugetThirdPartyEntryCount(NUGET_V1_LOCK)).toBe(4);
  });

  test("a type=Project entry is excluded — one less than the section total", () => {
    // 3 entries, 1 of which is the first-party project reference.
    expect(nugetThirdPartyEntryCount(NUGET_CPM_LOCK)).toBe(2);
  });

  test("an unknown-type entry COUNTS (exclusion by Project only — the collector's one exclusion, mirrored)", () => {
    const lock = JSON.stringify({
      version: 2,
      dependencies: {
        "net9.0": {
          "Weird.Package": { type: "SomeNewType", resolved: "1.0.0" },
        },
      },
    });
    expect(nugetThirdPartyEntryCount(lock)).toBe(1);
  });

  test("entries count across ALL dependency sections (multi-TFM)", () => {
    const lock = JSON.stringify({
      version: 2,
      dependencies: {
        "net8.0": { "Pkg.A": { type: "Direct", resolved: "1.0.0" } },
        "net9.0": { "Pkg.B": { type: "Direct", resolved: "2.0.0" } },
      },
    });
    expect(nugetThirdPartyEntryCount(lock)).toBe(2);
  });

  test("empty dependency sections are a positively-determined ZERO (warn+skip branch)", () => {
    expect(
      nugetThirdPartyEntryCount('{"version":2,"dependencies":{"net9.0":{}}}'),
    ).toBe(0);
  });

  test("garbage text → undefined, NOT 0 (unknown routes to the scan), never throws", () => {
    expect(nugetThirdPartyEntryCount("not json at all }{")).toBeUndefined();
    expect(nugetThirdPartyEntryCount("")).toBeUndefined();
    expect(nugetThirdPartyEntryCount('"just a string"')).toBeUndefined();
  });

  test("no dependencies map → undefined (a lock that proves nothing is unknown, not zero)", () => {
    expect(nugetThirdPartyEntryCount("{}")).toBeUndefined();
    // dependencies present but not an object → failed narrow → unknown.
    expect(
      nugetThirdPartyEntryCount('{"version":2,"dependencies":42}'),
    ).toBeUndefined();
  });

  test("an UNSUPPORTED lock version → undefined, never a positively-determined zero", () => {
    // The collector THROWS on version 3 (an unknown schema it refuses to
    // interpret); the counter must never claim it read one. An empty-looking
    // v3 lock must route to the scan — where the collector's loud version
    // error fires — never to the silent warn+skip branch.
    expect(
      nugetThirdPartyEntryCount('{"version":3,"dependencies":{"net9.0":{}}}'),
    ).toBeUndefined();
    // With entries the outcome is the same: unknown, route to the scan.
    expect(
      nugetThirdPartyEntryCount(
        JSON.stringify({
          version: 3,
          dependencies: {
            "net9.0": { "Pkg.A": { type: "Direct", resolved: "1.0.0" } },
          },
        }),
      ),
    ).toBeUndefined();
  });
});

describe("npmFirstPartyNames — link:true and local-path lockfile entries", () => {
  test("link:true and local-path entries yield the member name once", () => {
    // "node_modules/liba" link:true → "liba"; "packages/liba" name field → "liba".
    expect(npmFirstPartyNames(NPM_V3_LOCKFILE)).toEqual(new Set(["liba"]));
  });

  test("scoped link keys preserve the full @scope/name", () => {
    const lockfile = JSON.stringify({
      lockfileVersion: 3,
      packages: {
        "": {},
        "node_modules/@scope/liba": { resolved: "packages/liba", link: true },
      },
    });

    expect(npmFirstPartyNames(lockfile)).toEqual(new Set(["@scope/liba"]));
  });

  test("local-path entry without a name field falls back to the path basename", () => {
    const lockfile = JSON.stringify({
      lockfileVersion: 3,
      packages: {
        "": {},
        "packages/libb": { version: "0.2.0" },
      },
    });

    expect(npmFirstPartyNames(lockfile)).toEqual(new Set(["libb"]));
  });

  test("garbage yields an empty set, never throws", () => {
    expect(npmFirstPartyNames("not json }{")).toEqual(new Set());
    expect(npmFirstPartyNames("{}")).toEqual(new Set());
    expect(npmFirstPartyNames("")).toEqual(new Set());
  });
});

// pnpm v9 fixture — key shapes cited from 04.5-RESEARCH Pattern 3 (generated
// with pnpm 10.18.3 in the spike): v9 keys "  smol-toml@1.6.1:"; v6 keys
// carry a leading slash "  /smol-toml@1.6.1:" (Pitfall 5); keys may be quoted.
const PNPM_V9_LOCKFILE = [
  "lockfileVersion: '9.0'",
  "",
  "settings:",
  "  autoInstallPeers: true",
  "",
  "importers:",
  "",
  "  .:",
  "    dependencies:",
  "      smol-toml:",
  "        specifier: 1.6.1",
  "        version: 1.6.1",
  "",
  "  packages/liba:",
  "    dependencies:",
  "      array-find-index:",
  "        specifier: 1.0.2",
  "        version: 1.0.2",
  "",
  "packages:",
  "",
  "  array-find-index@1.0.2:",
  "    resolution: {integrity: sha512-aaa}",
  "",
  "  smol-toml@1.6.1:",
  "    resolution: {integrity: sha512-bbb}",
  "",
  "  '@types/node@1.0.0':",
  "    resolution: {integrity: sha512-ccc}",
  "",
].join("\n");

describe("pnpmThirdPartyEntryCount — packages: section key lines", () => {
  test("v9 two-space keys count; deeper-indented property lines do not", () => {
    expect(pnpmThirdPartyEntryCount(PNPM_V9_LOCKFILE)).toBe(3);
  });

  test("v6 leading-slash keys count identically", () => {
    const v6 = [
      "lockfileVersion: '6.0'",
      "",
      "packages:",
      "",
      "  /smol-toml@1.6.1:",
      "    resolution: {integrity: sha512-bbb}",
      "",
      "  '/@types/node@1.0.0':",
      "    resolution: {integrity: sha512-ccc}",
      "",
    ].join("\n");

    expect(pnpmThirdPartyEntryCount(v6)).toBe(2);
  });

  test("importers-only lockfile (no packages: section) → 0 (workspace-only warn+skip determination)", () => {
    const importersOnly = [
      "lockfileVersion: '9.0'",
      "",
      "importers:",
      "",
      "  .: {}",
      "",
      "  packages/liba:",
      "    dependencies:",
      "      libb:",
      "        specifier: workspace:*",
      "        version: link:../libb",
      "",
    ].join("\n");

    expect(pnpmThirdPartyEntryCount(importersOnly)).toBe(0);
  });

  test("CRLF lockfiles parse identically", () => {
    expect(
      pnpmThirdPartyEntryCount(PNPM_V9_LOCKFILE.replace(/\n/g, "\r\n")),
    ).toBe(3);
  });

  test("garbage never throws and counts 0", () => {
    expect(pnpmThirdPartyEntryCount("")).toBe(0);
    expect(pnpmThirdPartyEntryCount("not yaml at all }{ :::")).toBe(0);
    expect(pnpmThirdPartyEntryCount("packages: oops\n  weird@1.0.0:\n")).toBe(
      1,
    );
  });
});

describe("pnpmImporterNames — importer keys !== '.' (belt-and-braces)", () => {
  test("non-root importer keys yield their path basenames", () => {
    expect(pnpmImporterNames(PNPM_V9_LOCKFILE)).toEqual(new Set(["liba"]));
  });

  test("a '.'-only importers section yields an empty set", () => {
    const rootOnly = [
      "lockfileVersion: '9.0'",
      "",
      "importers:",
      "",
      "  .:",
      "    dependencies:",
      "      smol-toml:",
      "        specifier: 1.6.1",
      "        version: 1.6.1",
      "",
    ].join("\n");

    expect(pnpmImporterNames(rootOnly)).toEqual(new Set());
  });

  test("garbage yields an empty set, never throws", () => {
    expect(pnpmImporterNames("")).toEqual(new Set());
    expect(pnpmImporterNames("nonsense }{ :::")).toEqual(new Set());
  });
});

describe("yarnWorkspaceMembers — @workspace: resolution body lines", () => {
  test("direct entries: resolution body lines yield members with their literal relPaths", () => {
    const lockfile = [
      '"backend@workspace:backend":',
      "  version: 0.0.0-use.local",
      '  resolution: "backend@workspace:backend"',
      "  dependencies:",
      '    ms: "npm:2.1.3"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
      '"frontend@workspace:frontend":',
      "  version: 0.0.0-use.local",
      '  resolution: "frontend@workspace:frontend"',
      "  dependencies:",
      '    sax: "npm:1.4.1"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
    ].join("\n");

    expect(yarnWorkspaceMembers(lockfile)).toEqual([
      { name: "backend", relPath: "backend", hasDependencies: true },
      { name: "frontend", relPath: "frontend", hasDependencies: true },
    ]);
  });

  test("glob-resolved literal: a scoped name's lazy match extends past the leading @", () => {
    // The shape a `libs/*` workspaces glob produces once yarn resolves it.
    const lockfile = [
      '"@scope/util@workspace:libs/util":',
      "  version: 0.0.0-use.local",
      '  resolution: "@scope/util@workspace:libs/util"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
    ].join("\n");

    expect(yarnWorkspaceMembers(lockfile)).toEqual([
      { name: "@scope/util", relPath: "libs/util", hasDependencies: false },
    ]);
  });

  test("root entry: relPath '.' — a root-only lock yields exactly one member", () => {
    const lockfile = [
      '"demo-root@workspace:.":',
      "  version: 0.0.0-use.local",
      '  resolution: "demo-root@workspace:."',
      "  languageName: unknown",
      "  linkType: soft",
      "",
    ].join("\n");

    expect(yarnWorkspaceMembers(lockfile)).toEqual([
      { name: "demo-root", relPath: ".", hasDependencies: false },
    ]);
  });

  test("header range descriptors (workspace:^) never contribute a member", () => {
    // Cross-workspace deps make the header carry a RANGE descriptor
    // (workspace:^), not a path — only the resolution body line is real.
    const lockfile = [
      '"backend@workspace:^, backend@workspace:backend":',
      "  version: 0.0.0-use.local",
      '  resolution: "backend@workspace:backend"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
    ].join("\n");

    const members = yarnWorkspaceMembers(lockfile);
    expect(members).toEqual([
      { name: "backend", relPath: "backend", hasDependencies: false },
    ]);
    expect(members.some((m) => m.relPath === "^")).toBe(false);
  });

  test("hasDependencies: true when the entry's own block has a dependencies: line, false otherwise", () => {
    const lockfile = [
      '"backend@workspace:backend":',
      "  version: 0.0.0-use.local",
      '  resolution: "backend@workspace:backend"',
      "  dependencies:",
      '    ms: "npm:2.1.3"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
      '"frontend@workspace:frontend":',
      "  version: 0.0.0-use.local",
      '  resolution: "frontend@workspace:frontend"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
    ].join("\n");

    expect(yarnWorkspaceMembers(lockfile)).toEqual([
      { name: "backend", relPath: "backend", hasDependencies: true },
      { name: "frontend", relPath: "frontend", hasDependencies: false },
    ]);
  });

  test("a dependencies: block never bleeds across entries into a following member", () => {
    // backend's dependencies: block is followed by a NEW column-0 header
    // (frontend) before frontend's own (dependencies-less) body — frontend
    // must report false, not inherit backend's true.
    const lockfile = [
      '"backend@workspace:backend":',
      "  version: 0.0.0-use.local",
      '  resolution: "backend@workspace:backend"',
      "  dependencies:",
      '    ms: "npm:2.1.3"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
      '"frontend@workspace:frontend":',
      "  version: 0.0.0-use.local",
      '  resolution: "frontend@workspace:frontend"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
    ].join("\n");

    const members = yarnWorkspaceMembers(lockfile);
    expect(members.find((m) => m.name === "frontend")?.hasDependencies).toBe(
      false,
    );
  });

  test("dependenciesMeta: preceding dependencies: in the same entry does not confuse hasDependencies", () => {
    // dependenciesMeta always ACCOMPANIES a real dependencies: block in real
    // Yarn output, but the ORDER within the entry is not the parser's
    // assumption to break: dependenciesMeta appearing BEFORE dependencies:
    // must not suppress the true detection, and must not itself be mistaken
    // for a dependencies: line (DEPENDENCIES_BLOCK_RE is anchored to the
    // exact "dependencies:" line, never a prefix match).
    const lockfile = [
      '"backend@workspace:backend":',
      "  version: 0.0.0-use.local",
      '  resolution: "backend@workspace:backend"',
      "  dependenciesMeta:",
      "    ms:",
      "      optional: false",
      "  dependencies:",
      '    ms: "npm:2.1.3"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
    ].join("\n");

    expect(yarnWorkspaceMembers(lockfile)).toEqual([
      { name: "backend", relPath: "backend", hasDependencies: true },
    ]);
  });

  test("a peer-dependencies-only entry (no dependencies: block) reports hasDependencies false, never a silent scan", () => {
    const lockfile = [
      '"peerlib@workspace:libs/peerlib":',
      "  version: 0.0.0-use.local",
      '  resolution: "peerlib@workspace:libs/peerlib"',
      "  peerDependencies:",
      '    react: "npm:^18.0.0"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
    ].join("\n");

    expect(yarnWorkspaceMembers(lockfile)).toEqual([
      { name: "peerlib", relPath: "libs/peerlib", hasDependencies: false },
    ]);
  });

  test("unusual key order — languageName/linkType BEFORE resolution: — still yields the member (order within an entry is not assumed)", () => {
    const lockfile = [
      '"backend@workspace:backend":',
      "  languageName: unknown",
      "  linkType: soft",
      "  version: 0.0.0-use.local",
      '  resolution: "backend@workspace:backend"',
      "  dependencies:",
      '    ms: "npm:2.1.3"',
      "",
    ].join("\n");

    expect(yarnWorkspaceMembers(lockfile)).toEqual([
      { name: "backend", relPath: "backend", hasDependencies: true },
    ]);
  });

  test("unusual key order — dependencies: BEFORE resolution: (alphabetically sorted keys) — still records hasDependencies (the flag belongs to the BLOCK, not to lines after the resolution)", () => {
    // Yarn itself emits resolution: before dependencies:, but the parser
    // claims order within an entry is not its assumption (the test above
    // locks the mirror case). A YAML normalizer sorting keys puts
    // dependencies before resolution — losing the flag there would warn
    // and skip a workspace that DOES declare dependencies, a false
    // "declares no dependencies" under-coverage.
    const lockfile = [
      '"backend@workspace:backend":',
      "  dependencies:",
      '    ms: "npm:2.1.3"',
      "  languageName: unknown",
      "  linkType: soft",
      '  resolution: "backend@workspace:backend"',
      "  version: 0.0.0-use.local",
      "",
    ].join("\n");

    expect(yarnWorkspaceMembers(lockfile)).toEqual([
      { name: "backend", relPath: "backend", hasDependencies: true },
    ]);
  });

  test("CRLF lockfile text parses identically (trimEnd tolerance)", () => {
    const lockfile = [
      '"backend@workspace:backend":',
      "  version: 0.0.0-use.local",
      '  resolution: "backend@workspace:backend"',
      "  dependencies:",
      '    ms: "npm:2.1.3"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
    ].join("\r\n");

    expect(yarnWorkspaceMembers(lockfile)).toEqual([
      { name: "backend", relPath: "backend", hasDependencies: true },
    ]);
  });

  test("garbage/binary-ish text returns [] and never throws", () => {
    expect(yarnWorkspaceMembers("")).toEqual([]);
    expect(yarnWorkspaceMembers("not a lockfile at all }{ \0\x01\x02")).toEqual(
      [],
    );
  });

  test("a non-workspace protocol resolution (npm:) contributes nothing", () => {
    const lockfile = [
      '"ms@npm:2.1.3":',
      "  version: 2.1.3",
      '  resolution: "ms@npm:2.1.3"',
      "  languageName: node",
      "  linkType: hard",
      "",
    ].join("\n");

    expect(yarnWorkspaceMembers(lockfile)).toEqual([]);
  });

  test("hostile paths (traversal, absolute) are returned VERBATIM — containment is enforced at unit creation in the collect loop, not here", () => {
    const lockfile = [
      '"evil@workspace:../outside":',
      "  version: 0.0.0-use.local",
      '  resolution: "evil@workspace:../outside"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
      '"evil-abs@workspace:/etc/passwd":',
      "  version: 0.0.0-use.local",
      '  resolution: "evil-abs@workspace:/etc/passwd"',
      "  languageName: unknown",
      "  linkType: soft",
      "",
    ].join("\n");

    expect(yarnWorkspaceMembers(lockfile)).toEqual([
      { name: "evil", relPath: "../outside", hasDependencies: false },
      { name: "evil-abs", relPath: "/etc/passwd", hasDependencies: false },
    ]);
  });

  test.each([
    ["scoped name", "@acme/web-app", "packages/web-app"],
    [
      "dots, dashes, underscores, digits",
      "my.pkg-name_2",
      "libs/my.pkg-name_2",
    ],
    ["name differs from its directory path", "api", "services/backend-api"],
    ["deep multi-segment path", "web", "packages/apps/web"],
    ["unicode name/path", "café-app", "packages/café-app"],
    [
      "node_modules-adjacent name",
      "node-modules-helper",
      "packages/node-modules-helper",
    ],
    ["prefix-colliding pair, shorter member", "app", "app"],
    ["prefix-colliding pair, longer member", "app-server", "app-server"],
    ["a directory literally named dot", "dot-named", "dot"],
    [
      "uppercase name differing in case from a lowercase path",
      "Frontend",
      "Frontend",
    ],
  ])(
    "%s: %s@workspace:%s parses identically to a plain canonical member",
    (_label, name, relPath) => {
      const lockfile = [
        `"${name}@workspace:${relPath}":`,
        "  version: 0.0.0-use.local",
        `  resolution: "${name}@workspace:${relPath}"`,
        "  dependencies:",
        '    ms: "npm:2.1.3"',
        "  languageName: unknown",
        "  linkType: soft",
        "",
      ].join("\n");

      expect(yarnWorkspaceMembers(lockfile)).toEqual([
        { name, relPath, hasDependencies: true },
      ]);
    },
  );
});

describe("yarnWorkspaceMembers — a workspaces-monorepo fixture (workspace-berry.lock)", () => {
  test("the full fixture lock parses to exactly the three workspace members, in lockfile order, all with dependencies", () => {
    const lockfile = readFileSync(
      join(import.meta.dir, "fixtures", "workspace-berry.lock"),
      "utf8",
    );

    expect(yarnWorkspaceMembers(lockfile)).toEqual([
      { name: "demo-root", relPath: ".", hasDependencies: true },
      { name: "backend", relPath: "backend", hasDependencies: true },
      { name: "frontend", relPath: "frontend", hasDependencies: true },
    ]);
  });
});
