/**
 * Poetry prod-purl-set derivation (the python dev/prod split).
 *
 * cdxgen run with --no-install-deps emits NO poetry group marker on poetry
 * components — every poetry dep is otherwise classified prod. The fix mirrors
 * the yarn dual-run path: poetryProdPurlSet parses poetry.lock and returns the
 * `pkg:pypi/<pep503-name>@<version>` purl set of every package whose `groups`
 * array includes "main". merge.ts then derives occurrence dev = not in the set,
 * authoritative over the (absent) property markers.
 *
 * Locked properties:
 * - main-only package → in the prod set;
 * - dev-only package → NOT in the prod set;
 * - package in both "main" and "dev" → in the prod set (prod-wins);
 * - a name needing PEP-503 normalization (underscore/dot/uppercase run →
 *   single hyphen, lowercased) maps to the same purl cdxgen emits;
 * - absent `groups` key defaults to ["main"] (prod);
 * - garbage / non-TOML text yields an empty set, never throws.
 */

import { describe, expect, test } from "bun:test";

import { poetryProdPurlSet } from "../src/collectors/poetryLock";

/** Minimal poetry.lock with main-only, dev-only, and main+dev packages. */
const POETRY_LOCK = [
  "# generated by Poetry",
  "",
  "[[package]]",
  'name = "anyio"',
  'version = "4.12.1"',
  'groups = ["main"]',
  "",
  "[[package]]",
  'name = "jinja2-ansible-filters"',
  'version = "1.3.2"',
  'groups = ["dev"]',
  "",
  "[[package]]",
  'name = "shared-tool"',
  'version = "2.0.0"',
  'groups = ["main", "dev"]',
  "",
  // PEP-503 normalization target: Underscore.And-DOTS → underscore-and-dots
  "[[package]]",
  'name = "Underscore_And.DOTS"',
  'version = "3.1.0"',
  'groups = ["main"]',
  "",
  // No groups key at all → defaults to main (prod).
  "[[package]]",
  'name = "groupless-pkg"',
  'version = "1.0.0"',
  "",
].join("\n");

describe("poetryProdPurlSet", () => {
  test("includes main-only and excludes dev-only packages", () => {
    const set = poetryProdPurlSet(POETRY_LOCK);
    expect(set.has("pkg:pypi/anyio@4.12.1")).toBe(true);
    expect(set.has("pkg:pypi/jinja2-ansible-filters@1.3.2")).toBe(false);
  });

  test("a package in both main and dev is prod (prod-wins)", () => {
    const set = poetryProdPurlSet(POETRY_LOCK);
    expect(set.has("pkg:pypi/shared-tool@2.0.0")).toBe(true);
  });

  test("normalizes names per PEP 503 to match cdxgen's purl", () => {
    const set = poetryProdPurlSet(POETRY_LOCK);
    expect(set.has("pkg:pypi/underscore-and-dots@3.1.0")).toBe(true);
  });

  test("a package with no groups key defaults to prod", () => {
    const set = poetryProdPurlSet(POETRY_LOCK);
    expect(set.has("pkg:pypi/groupless-pkg@1.0.0")).toBe(true);
  });

  test("garbage text yields an empty set without throwing", () => {
    expect(poetryProdPurlSet("not a lockfile }{ :::").size).toBe(0);
    expect(poetryProdPurlSet("").size).toBe(0);
  });
});
