import { describe, expect, test } from "bun:test";

import { annotateFindings } from "../src/normalize/normalize";
import { renderCyclonedx } from "../src/render/cyclonedx";
import { renderNotices } from "../src/render/notices";
import { asRawLicense } from "./brandTestSupport";
import { claim, modelOf, pkg } from "./normalizeTestSupport";
import type { LicenseClaim } from "../src/model/dependencies";

/**
 * Canonicalization must be a MODEL invariant, not a per-scan-mode property: the same declared
 * claim set has to produce the same finding.expression (and the same generated bytes) whether or
 * not the intensive ScanCode assessment ran.
 *
 * Fixture: a package whose declared metadata carries two claims - a plain "MIT" claim and a dual
 * license "MIT OR Apache-2.0" claim (a realistic manifest shape: one field states the license, a
 * companion field restates it as an OR alternative). Read together the two claims are logically
 * equivalent to plain MIT - MIT alone already satisfies "MIT OR Apache-2.0", so the OR clause
 * contributes nothing (textbook absorption). The scancode-sourced claim below stands in for an
 * intensive scan whose in-depth elected answer for this exact package is "MIT" - the value is
 * already canonical, mirroring the real election.ts contract (the intensive lane canonicalizes
 * before a scancode claim is ever formed).
 */
const declaredClaims: LicenseClaim[] = [
  claim("MIT", "spdx-id"),
  claim("MIT OR Apache-2.0", "expression"),
];

const scancodeClaim: LicenseClaim = {
  raw: asRawLicense("MIT"),
  kind: "expression",
  source: "scancode",
};

describe("scan-mode canonicalization invariant", () => {
  test("the same declared claims produce the same finding.expression with or without a ScanCode assessment", () => {
    const nonIntensive = pkg("dual-license-pkg", "1.0.0", declaredClaims);
    const intensive = pkg("dual-license-pkg", "1.0.0", [...declaredClaims, scancodeClaim]);

    const nonIntensiveFinding = annotateFindings(modelOf(nonIntensive), []).model.packages[0]!
      .finding!;
    const intensiveFinding = annotateFindings(modelOf(intensive), []).model.packages[0]!.finding!;

    expect(nonIntensiveFinding.expression).toBe(intensiveFinding.expression);
  });

  test("THIRD_PARTY_NOTICES.md is byte-identical with or without a ScanCode assessment", () => {
    const nonIntensiveModel = annotateFindings(
      modelOf(pkg("dual-license-pkg", "1.0.0", declaredClaims)),
      [],
    ).model;
    const intensiveModel = annotateFindings(
      modelOf(pkg("dual-license-pkg", "1.0.0", [...declaredClaims, scancodeClaim])),
      [],
    ).model;

    expect(renderNotices(nonIntensiveModel)).toBe(renderNotices(intensiveModel));
  });

  test("the emitted CycloneDX license expression is the same with or without a ScanCode assessment", () => {
    const nonIntensiveModel = annotateFindings(
      modelOf(pkg("dual-license-pkg", "1.0.0", declaredClaims)),
      [],
    ).model;
    const intensiveModel = annotateFindings(
      modelOf(pkg("dual-license-pkg", "1.0.0", [...declaredClaims, scancodeClaim])),
      [],
    ).model;

    expect(renderCyclonedx(nonIntensiveModel)).toBe(renderCyclonedx(intensiveModel));
  });
});
